"""
Combine LOD OBJ files into a single FBX file for game engines and 3D applications.

This script processes multiple Level of Detail (LOD) OBJ files generated by the Grove
forest generation pipeline and combines them into a single FBX file with proper
LOD naming conventions for use in game engines like Unity, Unreal, or other 3D applications.

Usage:
    python combine_lods_to_fbx.py --input_dir data/bu/output --output_dir fbx_output

Requirements:
    - Blender (with bpy module available)
    - Install as: pip install bpy (or use Blender's built-in Python)

Author: Generated for The Grove forest generation pipeline
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

try:
    import bpy
    BLENDER_AVAILABLE = True
except ImportError:
    BLENDER_AVAILABLE = False
    print("Warning: Blender (bpy) not available. Please install Blender or use Blender's Python environment.")


class LODCombiner:
    """Combines multiple LOD OBJ files into a single FBX file."""
    
    # LOD level mapping for proper ordering
    LOD_ORDER = {
        'LOD0_Ultra': 0,
        'LOD1_High': 1, 
        'LOD2_Medium': 2,
        'LOD3_Low': 3,
        'LOD4_VeryLow': 4,
        'LOD5_Minimal': 5
    }
    
    def __init__(self, input_dir: Path, output_dir: Path, scale_factor: float = 1.0):
        """
        Initialize the LOD combiner.
        
        Args:
            input_dir: Directory containing LOD OBJ files
            output_dir: Directory to save combined FBX files
            scale_factor: Scale factor to apply to all meshes (default: 1.0)
        """
        self.input_dir = Path(input_dir)
        self.output_dir = Path(output_dir)
        self.scale_factor = scale_factor
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
    def parse_filename(self, filename: str) -> Optional[Tuple[str, str]]:
        """
        Parse filename to extract species and LOD level.
        
        Expected format: Species___LOD_Level.obj
        Example: Fagaceae___Beech_LOD0_Ultra.obj -> ('Fagaceae___Beech', 'LOD0_Ultra')
        
        Args:
            filename: OBJ filename to parse
            
        Returns:
            Tuple of (species_name, lod_level) or None if no match
        """
        # Pattern to match: Species_LOD_Level.obj
        pattern = r'^(.+?)_(LOD\d+_\w+)\.obj$'
        match = re.match(pattern, filename)
        
        if match:
            species = match.group(1)
            lod_level = match.group(2)
            return (species, lod_level)
        
        return None
    
    def group_lod_files(self) -> Dict[str, List[Tuple[str, Path]]]:
        """
        Group LOD files by species.
        
        Returns:
            Dictionary mapping species name to list of (lod_level, file_path) tuples
        """
        groups = {}
        
        for obj_file in self.input_dir.glob("*.obj"):
            parsed = self.parse_filename(obj_file.name)
            if parsed:
                species, lod_level = parsed
                if species not in groups:
                    groups[species] = []
                groups[species].append((lod_level, obj_file))
        
        # Sort each group by LOD order
        for species in groups:
            groups[species].sort(key=lambda x: self.LOD_ORDER.get(x[0], 999))
            
        return groups
    
    def clear_scene(self):
        """Clear all objects from the current Blender scene."""
        if not BLENDER_AVAILABLE:
            return
            
        # Select all mesh objects
        bpy.ops.object.select_all(action='SELECT')
        bpy.ops.object.delete(use_global=False)
        
        # Clear mesh data that's no longer used
        for mesh in bpy.data.meshes:
            bpy.data.meshes.remove(mesh)
    
    def import_obj(self, obj_path: Path, object_name: str) -> bool:
        """
        Import an OBJ file into Blender.
        
        Args:
            obj_path: Path to OBJ file
            object_name: Name to give the imported object
            
        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            return False
            
        try:
            # Import OBJ file
            bpy.ops.wm.obj_import(filepath=str(obj_path))
            
            # Get the imported object (should be the last selected)
            if bpy.context.selected_objects:
                obj = bpy.context.selected_objects[-1]
                obj.name = object_name
                
                # Apply scale if specified
                if self.scale_factor != 1.0:
                    obj.scale = (self.scale_factor, self.scale_factor, self.scale_factor)
                    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
                
                return True
                
        except Exception as e:
            print(f"Error importing {obj_path}: {e}")
            
        return False
    
    def setup_lod_group(self, species: str, lod_files: List[Tuple[str, Path]]) -> bool:
        """
        Set up LOD group for a species in Blender.
        
        Args:
            species: Species name
            lod_files: List of (lod_level, file_path) tuples
            
        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            return False
            
        success_count = 0
        
        for lod_level, obj_path in lod_files:
            # Create object name following LOD conventions
            object_name = f"{species}_{lod_level}"
            
            if self.import_obj(obj_path, object_name):
                success_count += 1
                print(f"  Imported: {object_name}")
            else:
                print(f"  Failed to import: {obj_path}")
        
        return success_count > 0
    
    def export_fbx(self, output_path: Path, species: str) -> bool:
        """
        Export current scene as FBX.
        
        Args:
            output_path: Path for output FBX file
            species: Species name for metadata
            
        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            return False
            
        try:
            # FBX export settings optimized for game engines
            bpy.ops.export_scene.fbx(
                filepath=str(output_path),
                use_selection=False,  # Export all objects
                use_active_collection=False,
                global_scale=1.0,  # Scale already applied to objects
                apply_unit_scale=True,
                apply_scale_options='FBX_SCALE_NONE',
                use_space_transform=True,
                bake_space_transform=False,
                object_types={'MESH'},
                use_mesh_modifiers=True,
                use_mesh_modifiers_render=True,
                mesh_smooth_type='OFF',  # Preserve original normals
                use_subsurf=False,
                use_mesh_edges=False,
                use_tspace=False,
                use_triangles=False,  # Keep quads if possible
                use_custom_props=False,
                add_leaf_bones=False,
                primary_bone_axis='Y',
                secondary_bone_axis='X',
                use_armature_deform_only=False,
                armature_nodetype='NULL',
                bake_anim=False,
                path_mode='AUTO',
                embed_textures=False,
                batch_mode='OFF'
            )
            
            return True
            
        except Exception as e:
            print(f"Error exporting FBX to {output_path}: {e}")
            return False
    
    def process_species(self, species: str, lod_files: List[Tuple[str, Path]]) -> bool:
        """
        Process a single species - combine LODs and export FBX.
        
        Args:
            species: Species name
            lod_files: List of (lod_level, file_path) tuples
            
        Returns:
            True if successful, False otherwise
        """
        print(f"\nProcessing species: {species}")
        print(f"Found {len(lod_files)} LOD levels")
        
        if not BLENDER_AVAILABLE:
            print("  Skipping: Blender not available")
            return False
        
        # Clear scene
        self.clear_scene()
        
        # Import all LOD files for this species
        if not self.setup_lod_group(species, lod_files):
            print(f"  Failed to import any LOD files for {species}")
            return False
        
        # Export as FBX
        output_path = self.output_dir / f"{species}_LODs.fbx"
        if self.export_fbx(output_path, species):
            print(f"  Successfully exported: {output_path}")
            return True
        else:
            print(f"  Failed to export FBX for {species}")
            return False
    
    def combine_all_lods(self) -> Dict[str, bool]:
        """
        Combine all LOD files into FBX files.
        
        Returns:
            Dictionary mapping species name to success status
        """
        if not BLENDER_AVAILABLE:
            print("Error: Blender (bpy) not available. Cannot proceed.")
            return {}
        
        # Group files by species
        species_groups = self.group_lod_files()
        
        if not species_groups:
            print("No LOD files found in input directory")
            return {}
        
        print(f"Found {len(species_groups)} species with LOD files:")
        for species, lod_files in species_groups.items():
            lod_levels = [lod[0] for lod in lod_files]
            print(f"  {species}: {', '.join(lod_levels)}")
        
        # Process each species
        results = {}
        for species, lod_files in species_groups.items():
            results[species] = self.process_species(species, lod_files)
        
        return results
    
    def create_manifest(self, results: Dict[str, bool]):
        """
        Create a manifest file describing the exported FBX files.
        
        Args:
            results: Dictionary mapping species name to success status
        """
        manifest_path = self.output_dir / "lod_manifest.txt"
        
        with open(manifest_path, 'w') as f:
            f.write("LOD FBX Export Manifest\n")
            f.write("=" * 50 + "\n\n")
            f.write(f"Generated from: {self.input_dir}\n")
            f.write(f"Output directory: {self.output_dir}\n")
            f.write(f"Scale factor: {self.scale_factor}\n\n")
            
            f.write("Exported FBX Files:\n")
            f.write("-" * 30 + "\n")
            
            successful = []
            failed = []
            
            for species, success in results.items():
                if success:
                    fbx_file = f"{species}_LODs.fbx"
                    f.write(f"✓ {fbx_file}\n")
                    successful.append(species)
                else:
                    f.write(f"✗ {species} (failed)\n")
                    failed.append(species)
            
            f.write("\nSummary:\n")
            f.write(f"  Successful: {len(successful)}\n")
            f.write(f"  Failed: {len(failed)}\n")
            
            if failed:
                f.write("\nFailed species:\n")
                for species in failed:
                    f.write(f"  - {species}\n")
        
        print(f"\nManifest written to: {manifest_path}")


def main():
    """Main function for command-line usage."""
    parser = argparse.ArgumentParser(
        description="Combine LOD OBJ files into FBX files for game engines"
    )
    
    parser.add_argument(
        "--input_dir", 
        type=str, 
        default="data/bu/output",
        help="Directory containing LOD OBJ files (default: data/bu/output)"
    )
    
    parser.add_argument(
        "--output_dir", 
        type=str, 
        default="fbx_output",
        help="Directory to save FBX files (default: fbx_output)"
    )
    
    parser.add_argument(
        "--scale", 
        type=float, 
        default=1.0,
        help="Scale factor to apply to all meshes (default: 1.0)"
    )
    
    parser.add_argument(
        "--check_only", 
        action="store_true",
        help="Only check for LOD files, don't process them"
    )
    
    args = parser.parse_args()
    
    # Convert to absolute paths
    input_dir = Path(args.input_dir).resolve()
    output_dir = Path(args.output_dir).resolve()
    
    if not input_dir.exists():
        print(f"Error: Input directory does not exist: {input_dir}")
        return 1
    
    print("LOD to FBX Combiner")
    print(f"Input directory: {input_dir}")
    print(f"Output directory: {output_dir}")
    print(f"Scale factor: {args.scale}")
    
    # Check Blender availability
    if not BLENDER_AVAILABLE:
        print("\nError: Blender (bpy) not available.")
        print("To install Blender Python API:")
        print("  pip install bpy")
        print("Or run this script with Blender's Python:")
        print("  /path/to/blender --background --python combine_lods_to_fbx.py")
        return 1
    
    # Initialize combiner
    combiner = LODCombiner(input_dir, output_dir, args.scale)
    
    # Check for LOD files
    species_groups = combiner.group_lod_files()
    
    if not species_groups:
        print("\nNo LOD files found in input directory")
        print("Looking for files matching pattern: *_LOD*_*.obj")
        return 1
    
    print(f"\nFound {len(species_groups)} species with LOD files:")
    for species, lod_files in species_groups.items():
        lod_levels = [lod[0] for lod in lod_files]
        print(f"  {species}: {', '.join(lod_levels)}")
    
    if args.check_only:
        print("\nCheck complete (--check_only specified)")
        return 0
    
    # Process all species
    results = combiner.combine_all_lods()
    
    # Create manifest
    combiner.create_manifest(results)
    
    # Print summary
    successful = sum(1 for success in results.values() if success)
    total = len(results)
    
    print("\nProcessing complete:")
    print(f"  Successful: {successful}/{total}")
    print(f"  Output directory: {output_dir}")
    
    return 0 if successful == total else 1


if __name__ == "__main__":
    sys.exit(main())
