"""
Combine LOD model files (OBJ/USD) into a single FBX file for game engines and 3D applications.

This script processes multiple Level of Detail (LOD) model files generated by the Grove
forest generation pipeline and combines them into a single FBX file with proper
LOD naming conventions for use in game engines like Unity, Unreal, or other 3D applications.

Supported formats: OBJ, USD

Usage:
    python fbx.py --input_dir data/output --output_dir data/output/fbx

Requirements:
    - Blender (with bpy module available)
    - Install as: pip install bpy (or use Blender's built-in Python)

Author: Generated for The Grove forest generation pipeline
"""

import argparse
import logging
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

try:
    import bpy

    BLENDER_AVAILABLE = True
    logger.info("Blender (bpy) module imported successfully")
except ImportError as e:
    BLENDER_AVAILABLE = False
    logger.warning(f"Blender (bpy) module not available: {e}")


class BlenderOperationError(Exception):
    """Exception raised when Blender operations fail."""
    pass


class LODCombiner:
    """Combines multiple LOD model files (OBJ/USD) into a single FBX file."""

    # LOD level mapping for proper ordering
    LOD_ORDER = {
        "LOD0_Ultra": 0,
        "LOD1_High": 1,
        "LOD2_Medium": 2,
        "LOD3_Low": 3,
        "LOD4_VeryLow": 4,
        "LOD5_Minimal": 5,
    }

    # Supported file formats
    SUPPORTED_FORMATS = {".obj", ".usd", ".usda", ".usdc"}

    def __init__(self, input_dir: Path, output_dir: Path, scale_factor: float = 1.0):
        """
        Initialize the LOD combiner.

        Args:
            input_dir: Directory containing LOD model files (OBJ/USD)
            output_dir: Directory to save combined FBX files
            scale_factor: Scale factor to apply to all meshes (default: 1.0)
        """
        self.input_dir = Path(input_dir)
        self.output_dir = Path(output_dir)
        self.scale_factor = scale_factor
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def parse_filename(self, filename: str) -> Optional[Tuple[str, str]]:
        """
        Parse filename to extract species and LOD level.

        Expected formats:
        - Species___LOD_Level.obj
        - Species___tree_001.usd (for individual trees)

        Examples:
        - Fagaceae___Beech_LOD0_Ultra.obj -> ('Fagaceae___Beech', 'LOD0_Ultra')
        - Fagaceae___Beech_tree_001.usd -> ('Fagaceae___Beech', 'tree_001')

        Args:
            filename: Model filename to parse

        Returns:
            Tuple of (species_name, lod_level_or_tree_id) or None if no match
        """
        # Get file extension
        file_ext = Path(filename).suffix.lower()
        if file_ext not in self.SUPPORTED_FORMATS:
            return None

        # Pattern to match LOD files: Species_LOD_Level.ext
        lod_pattern = r"^(.+?)_(LOD\d+_\w+)\." + file_ext[1:] + r"$"
        lod_match = re.match(lod_pattern, filename)

        if lod_match:
            species = lod_match.group(1)
            lod_level = lod_match.group(2)
            return (species, lod_level)

        # Pattern to match individual tree files: Species_tree_###.ext
        tree_pattern = r"^(.+?)_(tree_\d+)\." + file_ext[1:] + r"$"
        tree_match = re.match(tree_pattern, filename)

        if tree_match:
            species = tree_match.group(1)
            tree_id = tree_match.group(2)
            return (species, tree_id)

        return None

    def group_lod_files(self) -> Dict[str, List[Tuple[str, Path]]]:
        """
        Group model files by species.

        Returns:
            Dictionary mapping species name to list of (lod_level_or_tree_id, file_path) tuples
        """
        groups = {}

        # Check all supported file formats
        for file_ext in self.SUPPORTED_FORMATS:
            for model_file in self.input_dir.glob(f"*{file_ext}"):
                parsed = self.parse_filename(model_file.name)
                if parsed:
                    species, identifier = parsed
                    if species not in groups:
                        groups[species] = []
                    groups[species].append((identifier, model_file))

        # Sort each group by LOD order
        for species in groups:
            groups[species].sort(key=lambda x: self.LOD_ORDER.get(x[0], 999))

        return groups

    def clear_scene(self):
        """Clear all objects from the current Blender scene."""
        if not BLENDER_AVAILABLE:
            raise BlenderOperationError("Blender is not available")

        try:
            # Select all mesh objects
            bpy.ops.object.select_all(action="SELECT")
            bpy.ops.object.delete(use_global=False)

            # Clear mesh data that's no longer used
            for mesh in bpy.data.meshes:
                bpy.data.meshes.remove(mesh)
            
            logger.debug("Scene cleared successfully")
        except Exception as e:
            raise BlenderOperationError(f"Failed to clear scene: {e}")

    def import_model(self, model_path: Path, object_name: str) -> bool:
        """
        Import a model file (OBJ/USD) into Blender.

        Args:
            model_path: Path to model file (OBJ/USD)
            object_name: Name to give the imported object

        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            logger.error("Blender is not available for import operations")
            return False

        if not model_path.exists():
            logger.error(f"Model file does not exist: {model_path}")
            return False

        try:
            file_ext = model_path.suffix.lower()

            # Import based on file extension
            if file_ext == ".obj":
                bpy.ops.wm.obj_import(filepath=str(model_path))
                logger.debug(f"Imported OBJ file: {model_path}")
            elif file_ext in {".usd", ".usda", ".usdc"}:
                bpy.ops.wm.usd_import(filepath=str(model_path))
                logger.debug(f"Imported USD file: {model_path}")
            else:
                logger.error(f"Unsupported file format: {file_ext}")
                return False

            # Get the imported object (should be the last selected)
            if bpy.context.selected_objects:
                obj = bpy.context.selected_objects[-1]
                obj.name = object_name

                # Apply scale if specified
                if self.scale_factor != 1.0:
                    obj.scale = (
                        self.scale_factor,
                        self.scale_factor,
                        self.scale_factor,
                    )
                    bpy.ops.object.transform_apply(
                        location=False, rotation=False, scale=True
                    )

                logger.debug(f"Successfully imported and named object: {object_name}")
                return True
            else:
                logger.error(f"No objects were imported from {model_path}")
                return False

        except Exception as e:
            logger.error(f"Failed to import model {model_path}: {e}")
            return False

    def setup_lod_group(
        self, species: str, model_files: List[Tuple[str, Path]]
    ) -> bool:
        """
        Set up model group for a species in Blender.

        Args:
            species: Species name
            model_files: List of (identifier, file_path) tuples (LOD levels or tree IDs)

        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            return False

        success_count = 0

        for identifier, model_path in sorted(
            model_files, key=lambda x: self.LOD_ORDER.get(x[0], 999)
        ):
            # Create object name following conventions
            # For LOD files: Species_LOD_Level
            # For individual trees: Species_tree_id
            object_name = f"{species}_{identifier}"

            if self.import_model(model_path, object_name):
                success_count += 1

        return success_count > 0

    def export_fbx(self, output_path: Path, species: str) -> bool:
        """
        Export current scene as FBX.

        Args:
            output_path: Path for output FBX file
            species: Species name for metadata

        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            logger.error("Blender is not available for FBX export")
            return False

        try:
            # Ensure output directory exists
            output_path.parent.mkdir(parents=True, exist_ok=True)
            
            # FBX export settings optimized for game engines
            bpy.ops.export_scene.fbx(
                filepath=str(output_path),
                use_selection=False,  # Export all objects
                use_active_collection=False,
                global_scale=1.0,  # Scale already applied to objects
                apply_unit_scale=True,
                apply_scale_options="FBX_SCALE_NONE",
                use_space_transform=True,
                bake_space_transform=False,
                object_types={"MESH"},
                use_mesh_modifiers=True,
                use_mesh_modifiers_render=True,
                mesh_smooth_type="OFF",  # Preserve original normals
                use_subsurf=False,
                use_mesh_edges=False,
                use_tspace=False,
                use_triangles=False,  # Keep quads if possible
                use_custom_props=False,
                add_leaf_bones=False,
                primary_bone_axis="Y",
                secondary_bone_axis="X",
                use_armature_deform_only=False,
                armature_nodetype="NULL",
                bake_anim=False,
                path_mode="AUTO",
                embed_textures=False,
                batch_mode="OFF",
            )

            logger.info(f"Successfully exported FBX: {output_path}")
            return True

        except Exception as e:
            logger.error(f"Failed to export FBX {output_path}: {e}")
            return False

    def process_species(
        self, species: str, model_files: List[Tuple[str, Path]]
    ) -> bool:
        """
        Process a single species - combine models and export FBX.

        Args:
            species: Species name
            model_files: List of (identifier, file_path) tuples (LOD levels or tree IDs)

        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            return False

        # Clear scene
        self.clear_scene()

        # Import all model files for this species
        if not self.setup_lod_group(species, model_files):
            return False

        # Export as FBX
        output_path = self.output_dir / f"{species}_Models.fbx"
        return self.export_fbx(output_path, species)

    def combine_all_lods(self) -> Dict[str, bool]:
        """
        Combine all LOD files into FBX files.

        Returns:
            Dictionary mapping species name to success status
        """
        if not BLENDER_AVAILABLE:
            return {}

        # Group files by species
        species_groups = self.group_lod_files()

        if not species_groups:
            return {}

        # Process each species
        results = {}
        for species, lod_files in species_groups.items():
            results[species] = self.process_species(species, lod_files)

        return results

    def create_manifest(self, results: Dict[str, bool]):
        """
        Create a manifest file describing the exported FBX files.

        Args:
            results: Dictionary mapping species name to success status
        """
        manifest_path = self.output_dir / "lod_manifest.txt"

        with open(manifest_path, "w") as f:
            f.write("LOD FBX Export Manifest\n")
            f.write("=" * 50 + "\n\n")
            f.write(f"Generated from: {self.input_dir}\n")
            f.write(f"Output directory: {self.output_dir}\n")
            f.write(f"Scale factor: {self.scale_factor}\n\n")

            f.write("Exported FBX Files:\n")
            f.write("-" * 30 + "\n")

            successful = []
            failed = []

            for species, success in results.items():
                if success:
                    fbx_file = f"{species}_Models.fbx"
                    f.write(f"✓ {fbx_file}\n")
                    successful.append(species)
                else:
                    f.write(f"✗ {species} (failed)\n")
                    failed.append(species)

            f.write("\nSummary:\n")
            f.write(f"  Successful: {len(successful)}\n")
            f.write(f"  Failed: {len(failed)}\n")

            if failed:
                f.write("\nFailed species:\n")
                for species in failed:
                    f.write(f"  - {species}\n")


def main():
    """Main function for command-line usage."""
    parser = argparse.ArgumentParser(
        description="Combine LOD OBJ files into FBX files for game engines"
    )

    parser.add_argument(
        "--input_dir",
        type=str,
        default="data/output",
        help="Directory containing LOD OBJ files (default: data/output)",
    )

    parser.add_argument(
        "--output_dir",
        type=str,
        default="data/output/fbx",
        help="Directory to save FBX files (default: data/output/fbx)",
    )

    parser.add_argument(
        "--scale",
        type=float,
        default=1.0,
        help="Scale factor to apply to all meshes (default: 1.0)",
    )

    parser.add_argument(
        "--check_only",
        action="store_true",
        help="Only check for LOD files, don't process them",
    )

    args = parser.parse_args()

    # Convert to absolute paths
    input_dir = Path(args.input_dir).resolve()
    output_dir = Path(args.output_dir).resolve()

    if not input_dir.exists():
        return 1

    # Check Blender availability
    if not BLENDER_AVAILABLE:
        return 1

    # Initialize combiner
    combiner = LODCombiner(input_dir, output_dir, args.scale)

    # Check for LOD files
    species_groups = combiner.group_lod_files()

    if not species_groups:
        return 1

    if args.check_only:
        return 0

    # Process all species
    results = combiner.combine_all_lods()

    # Create manifest
    combiner.create_manifest(results)

    # Return based on success rate
    successful = sum(1 for success in results.values() if success)
    total = len(results)

    return 0 if successful == total else 1


if __name__ == "__main__":
    sys.exit(main())
