"""
Combine LOD model files (OBJ/USD) into a single FBX file with twig instancing for Unity.

This script processes multiple Level of Detail (LOD) model files generated by the Grove
forest generation pipeline and combines them into a single FBX file with proper
LOD naming conventions and twig instancing for use in Unity and other game engines.

Supported formats: OBJ, USD
Twig instancing: Automatically places twig instances at branch ends using Grove's
triangle-based placement system and .blend twig models from the twigs directory.

Usage:
    # Import and use the LODCombiner class in your Python code
    from growpy.io.fbx import LODCombiner
    combiner = LODCombiner(input_dir, output_dir)
    results = combiner.combine_all_lods()

Requirements:
    - Blender (with bpy module available)
    - Install as: pip install bpy (or use Blender's built-in Python)

Author: Generated for The Grove forest generation pipeline
"""

import logging
import re
import math
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

try:
    import bpy
    import bmesh
    from mathutils import Vector as BlenderVector, Matrix

    BLENDER_AVAILABLE = True
    logger.info("Blender (bpy) module imported successfully")
except ImportError as e:
    BLENDER_AVAILABLE = False
    logger.warning(f"Blender (bpy) module not available: {e}")


class BlenderOperationError(Exception):
    """Exception raised when Blender operations fail."""
    pass


class LODCombiner:
    """Combines multiple LOD model files (OBJ/USD) into a single FBX file with twig instancing."""

    # LOD level mapping for proper ordering
    LOD_ORDER = {
        "LOD0_Ultra": 0,
        "LOD1_High": 1,
        "LOD2_Medium": 2,
        "LOD3_Low": 3,
        "LOD4_VeryLow": 4,
        "LOD5_Minimal": 5,
    }

    # Supported file formats
    SUPPORTED_FORMATS = {".obj", ".usd", ".usda", ".usdc"}
    
    # Twig type mapping for different placement locations
    TWIG_TYPES = {
        'long': 'apical',      # End/terminal twigs
        'short': 'lateral',    # Side twigs
        'upward': 'upward',    # Upward-facing twigs
        'dead': 'dead'         # Dead branch twigs
    }

    def __init__(self, input_dir: Path, output_dir: Path, scale_factor: float = 1.0, twigs_dir: Path = None):
        """
        Initialize the LOD combiner.

        Args:
            input_dir: Directory containing LOD model files (OBJ/USD)
            output_dir: Directory to save combined FBX files
            scale_factor: Scale factor to apply to all meshes (default: 1.0)
            twigs_dir: Directory containing twig .blend files (default: auto-detect)
        """
        self.input_dir = Path(input_dir)
        self.output_dir = Path(output_dir)
        self.scale_factor = scale_factor
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Auto-detect twigs directory if not provided
        if twigs_dir is None:
            # Try to find twigs directory in common locations
            possible_twigs = [
                self.input_dir / "twigs",  # In the input directory
                self.input_dir.parent / "twigs",  # In the parent of input directory
                Path(__file__).parent.parent.parent / "the_grove_22" / "twigs",  # Relative to growpy package
                Path.cwd() / "src" / "the_grove_22" / "twigs",  # From project root
                Path(__file__).resolve().parent.parent.parent.parent / "src" / "the_grove_22" / "twigs"  # Alternative from package location
            ]
            for possible_dir in possible_twigs:
                if possible_dir.exists():
                    self.twigs_dir = possible_dir
                    break
            else:
                logger.warning("Could not auto-detect twigs directory. Twigs will not be added.")
                self.twigs_dir = None
        else:
            self.twigs_dir = Path(twigs_dir)
            
        self.loaded_twigs = {}  # Cache for loaded twig objects

    def parse_filename(self, filename: str) -> Optional[Tuple[str, str]]:
        """
        Parse filename to extract species and LOD level.

        Expected formats:
        - Species___LOD_Level.obj
        - Species___tree_001.usd (for individual trees)

        Examples:
        - Fagaceae___Beech_LOD0_Ultra.obj -> ('Fagaceae___Beech', 'LOD0_Ultra')
        - Fagaceae___Beech_tree_001.usd -> ('Fagaceae___Beech', 'tree_001')

        Args:
            filename: Model filename to parse

        Returns:
            Tuple of (species_name, lod_level_or_tree_id) or None if no match
        """
        # Get file extension
        file_ext = Path(filename).suffix.lower()
        if file_ext not in self.SUPPORTED_FORMATS:
            return None

        # Pattern to match LOD files: Species_LOD_Level.ext
        lod_pattern = r"^(.+?)_(LOD\d+_\w+)\." + file_ext[1:] + r"$"
        lod_match = re.match(lod_pattern, filename)

        if lod_match:
            species = lod_match.group(1)
            lod_level = lod_match.group(2)
            return (species, lod_level)

        # Pattern to match individual tree files: Species_tree_###.ext
        tree_pattern = r"^(.+?)_(tree_\d+)\." + file_ext[1:] + r"$"
        tree_match = re.match(tree_pattern, filename)

        if tree_match:
            species = tree_match.group(1)
            tree_id = tree_match.group(2)
            return (species, tree_id)

        return None

    def find_twig_for_species(self, species_name: str) -> Optional[Path]:
        """
        Find the most appropriate twig for a given species using mapping system.
        
        Args:
            species_name: Species name to find twig for
            
        Returns:
            Path to .blend file or None if no suitable twig found
        """
        if not self.twigs_dir or not self.twigs_dir.exists():
            return None
        
        # Try to use the mapping system first
        twig_name = None
        try:
            from ..core.mapping import get_twig_name, get_species_mapper
            
            # Get mapped twig name
            twig_name = get_twig_name(species_name)
            
            # If no direct mapping, try fallback logic
            if not twig_name:
                mapper = get_species_mapper()
                twig_name = mapper.get_fallback_twig(species_name)
                if twig_name:
                    logger.info(f"Using fallback twig '{twig_name}' for species '{species_name}'")
            else:
                logger.debug(f"Mapped species '{species_name}' to twig '{twig_name}'")
                
        except ImportError:
            logger.warning("Species mapping not available, using legacy twig detection")
        
        # If we have a mapped twig name, try to find it
        if twig_name:
            twig_path = self._find_twig_by_name(twig_name)
            if twig_path:
                return twig_path
            else:
                logger.warning(f"Mapped twig '{twig_name}' not found in twigs directory")
        
        # Fallback to legacy detection method
        return self._legacy_find_twig(species_name)
    
    def _find_twig_by_name(self, twig_name: str) -> Optional[Path]:
        """Find twig .blend file by twig name."""
        if not self.twigs_dir or not self.twigs_dir.exists():
            return None
            
        # Look for exact twig directory match
        twig_dir = self.twigs_dir / twig_name
        if twig_dir.exists() and twig_dir.is_dir():
            blend_files = list(twig_dir.glob("*.blend"))
            if blend_files:
                return blend_files[0]
        
        # Look for partial matches (case-insensitive)
        for twig_dir in self.twigs_dir.iterdir():
            if not twig_dir.is_dir():
                continue
            if twig_name.lower() in twig_dir.name.lower():
                blend_files = list(twig_dir.glob("*.blend"))
                if blend_files:
                    return blend_files[0]
        
        return None
    
    def _legacy_find_twig(self, species_name: str) -> Optional[Path]:
        """Legacy twig finding method (for backward compatibility)."""
        # Extract main species name (e.g., "Fagaceae___Beech" -> "Beech")
        species_parts = species_name.split("___")
        if len(species_parts) > 1:
            main_species = species_parts[-1]
        else:
            # Also try " - " separator (common in preset names)
            if " - " in species_name:
                main_species = species_name.split(" - ")[-1]
            else:
                main_species = species_name
            
        # Look for matching twig directories
        for twig_dir in self.twigs_dir.iterdir():
            if not twig_dir.is_dir():
                continue
                
            # Check if species name matches twig directory name
            if main_species.lower() in twig_dir.name.lower():
                # Find .blend file in the twig directory
                blend_files = list(twig_dir.glob("*.blend"))
                if blend_files:
                    return blend_files[0]  # Return first .blend file
                    
        # Final fallback: try to find any twig
        for twig_dir in self.twigs_dir.iterdir():
            if not twig_dir.is_dir():
                continue
            blend_files = list(twig_dir.glob("*.blend"))
            if blend_files:
                logger.info(f"Using generic fallback twig {twig_dir.name} for species {species_name}")
                return blend_files[0]
                
        return None

    def load_twig_from_blend(self, blend_file: Path) -> Optional[str]:
        """
        Load a twig object from a .blend file.
        
        Args:
            blend_file: Path to .blend file containing twig
            
        Returns:
            Name of the loaded twig object or None if failed
        """
        if not BLENDER_AVAILABLE:
            return None
            
        if blend_file in self.loaded_twigs:
            return self.loaded_twigs[blend_file]
            
        try:
            # Append objects from the .blend file
            with bpy.data.libraries.load(str(blend_file)) as (data_from, data_to):
                data_to.objects = data_from.objects
                
            # Find the main twig object (usually the largest mesh)
            twig_object = None
            max_vertices = 0
            
            for obj in data_to.objects:
                if obj and obj.type == 'MESH' and obj.data:
                    vertex_count = len(obj.data.vertices)
                    if vertex_count > max_vertices:
                        max_vertices = vertex_count
                        twig_object = obj
                        
            if twig_object:
                # Link to current scene
                bpy.context.collection.objects.link(twig_object)
                
                # Ensure proper orientation (X-axis forward as per Grove documentation)
                # The twig should already be oriented correctly in the .blend file
                
                # Cache the loaded twig
                self.loaded_twigs[blend_file] = twig_object.name
                logger.debug(f"Loaded twig from {blend_file.name}: {twig_object.name}")
                return twig_object.name
                
        except Exception as e:
            logger.error(f"Failed to load twig from {blend_file}: {e}")
            
        return None

    def calculate_triangle_center(self, model, face_indices: List[int]) -> Tuple[float, float, float]:
        """
        Calculate the center point of a triangle face.
        
        Args:
            model: Grove model object
            face_indices: List of vertex indices for the face
            
        Returns:
            Tuple of (x, y, z) coordinates
        """
        if len(face_indices) < 3:
            return (0.0, 0.0, 0.0)
            
        # Get the first 3 vertices to form a triangle
        v1 = model.points[face_indices[0]]
        v2 = model.points[face_indices[1]]
        v3 = model.points[face_indices[2]]
        
        # Calculate centroid
        center_x = (v1.x + v2.x + v3.x) / 3.0
        center_y = (v1.y + v2.y + v3.y) / 3.0
        center_z = (v1.z + v2.z + v3.z) / 3.0
        
        return (center_x, center_y, center_z)

    def calculate_triangle_normal(self, model, face_indices: List[int]) -> Tuple[float, float, float]:
        """
        Calculate the normal vector of a triangle face.
        
        Args:
            model: Grove model object
            face_indices: List of vertex indices for the face
            
        Returns:
            Tuple of (x, y, z) normal vector
        """
        if len(face_indices) < 3:
            return (1.0, 0.0, 0.0)  # Default X-axis forward
            
        # Get the first 3 vertices to form a triangle
        v1 = model.points[face_indices[0]]
        v2 = model.points[face_indices[1]]
        v3 = model.points[face_indices[2]]
        
        # Calculate two edge vectors
        edge1 = (v2.x - v1.x, v2.y - v1.y, v2.z - v1.z)
        edge2 = (v3.x - v1.x, v3.y - v1.y, v3.z - v1.z)
        
        # Calculate cross product (normal)
        normal_x = edge1[1] * edge2[2] - edge1[2] * edge2[1]
        normal_y = edge1[2] * edge2[0] - edge1[0] * edge2[2]
        normal_z = edge1[0] * edge2[1] - edge1[1] * edge2[0]
        
        # Normalize
        length = math.sqrt(normal_x**2 + normal_y**2 + normal_z**2)
        if length > 0:
            normal_x /= length
            normal_y /= length
            normal_z /= length
        else:
            return (1.0, 0.0, 0.0)  # Default X-axis forward
            
        return (normal_x, normal_y, normal_z)

    def instance_twigs_on_model(self, model, species_name: str) -> bool:
        """
        Instance twigs on the model based on face attributes.
        
        Args:
            model: Grove model with face attributes
            species_name: Species name to find appropriate twig
            
        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            return False
            
        # Find appropriate twig for this species
        twig_file = self.find_twig_for_species(species_name)
        if not twig_file:
            logger.warning(f"No twig found for species {species_name}")
            return False
            
        # Load the twig
        twig_name = self.load_twig_from_blend(twig_file)
        if not twig_name:
            logger.error(f"Failed to load twig for species {species_name}")
            return False
            
        twig_object = bpy.data.objects.get(twig_name)
        if not twig_object:
            logger.error(f"Twig object {twig_name} not found in scene")
            return False
            
        # Process different types of twig placement
        twig_types = [
            ('long', model.face_attribute_twig_long),
            ('short', model.face_attribute_twig_short),
            ('upward', model.face_attribute_twig_upward),
            ('dead', model.face_attribute_twig_dead)
        ]
        
        instance_count = 0
        
        for twig_type, face_attributes in twig_types:
            if not face_attributes:
                continue
                
            for face_index, should_place_twig in enumerate(face_attributes):
                if not should_place_twig:
                    continue
                    
                if face_index >= len(model.faces):
                    continue
                    
                # Get triangle center and normal
                face_indices = model.faces[face_index]
                center = self.calculate_triangle_center(model, face_indices)
                normal = self.calculate_triangle_normal(model, face_indices)
                
                # Create instance of the twig
                instance = twig_object.copy()
                instance.data = twig_object.data.copy()
                instance.name = f"{twig_name}_{twig_type}_{instance_count:04d}"
                
                # Position the instance
                instance.location = center
                
                # Orient the instance
                # The twig should point in the direction of the normal
                # Grove twigs are oriented with X-axis forward
                target_vector = BlenderVector(normal)
                if target_vector.length > 0:
                    # Create rotation matrix to align X-axis with target
                    x_axis = BlenderVector((1, 0, 0))
                    rotation_matrix = x_axis.rotation_difference(target_vector).to_matrix().to_4x4()
                    instance.matrix_world = Matrix.Translation(center) @ rotation_matrix
                
                # Apply scale
                if self.scale_factor != 1.0:
                    instance.scale = (self.scale_factor, self.scale_factor, self.scale_factor)
                
                # Link to scene
                bpy.context.collection.objects.link(instance)
                instance_count += 1
                
        logger.info(f"Instanced {instance_count} twigs for species {species_name}")
        return instance_count > 0

    def group_lod_files(self) -> Dict[str, List[Tuple[str, Path]]]:
        """
        Group model files by species.

        Returns:
            Dictionary mapping species name to list of (lod_level_or_tree_id, file_path) tuples
        """
        groups = {}

        # Check all supported file formats
        for file_ext in self.SUPPORTED_FORMATS:
            for model_file in self.input_dir.glob(f"*{file_ext}"):
                parsed = self.parse_filename(model_file.name)
                if parsed:
                    species, identifier = parsed
                    if species not in groups:
                        groups[species] = []
                    groups[species].append((identifier, model_file))

        # Sort each group by LOD order
        for species in groups:
            groups[species].sort(key=lambda x: self.LOD_ORDER.get(x[0], 999))

        return groups

    def clear_scene(self):
        """Clear all objects from the current Blender scene."""
        if not BLENDER_AVAILABLE:
            raise BlenderOperationError("Blender is not available")

        try:
            # Select all mesh objects
            bpy.ops.object.select_all(action="SELECT")
            bpy.ops.object.delete(use_global=False)

            # Clear mesh data that's no longer used
            for mesh in bpy.data.meshes:
                bpy.data.meshes.remove(mesh)
            
            logger.debug("Scene cleared successfully")
        except Exception as e:
            raise BlenderOperationError(f"Failed to clear scene: {e}")

    def import_model(self, model_path: Path, object_name: str) -> bool:
        """
        Import a model file (OBJ/USD) into Blender.

        Args:
            model_path: Path to model file (OBJ/USD)
            object_name: Name to give the imported object

        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            logger.error("Blender is not available for import operations")
            return False

        if not model_path.exists():
            logger.error(f"Model file does not exist: {model_path}")
            return False

        try:
            file_ext = model_path.suffix.lower()

            # Import based on file extension
            if file_ext == ".obj":
                bpy.ops.wm.obj_import(filepath=str(model_path))
                logger.debug(f"Imported OBJ file: {model_path}")
            elif file_ext in {".usd", ".usda", ".usdc"}:
                bpy.ops.wm.usd_import(filepath=str(model_path))
                logger.debug(f"Imported USD file: {model_path}")
            else:
                logger.error(f"Unsupported file format: {file_ext}")
                return False

            # Get the imported object (should be the last selected)
            if bpy.context.selected_objects:
                obj = bpy.context.selected_objects[-1]
                obj.name = object_name

                # Apply scale if specified
                if self.scale_factor != 1.0:
                    obj.scale = (
                        self.scale_factor,
                        self.scale_factor,
                        self.scale_factor,
                    )
                    bpy.ops.object.transform_apply(
                        location=False, rotation=False, scale=True
                    )

                logger.debug(f"Successfully imported and named object: {object_name}")
                return True
            else:
                logger.error(f"No objects were imported from {model_path}")
                return False

        except Exception as e:
            logger.error(f"Failed to import model {model_path}: {e}")
            return False

    def setup_lod_group(
        self, species: str, model_files: List[Tuple[str, Path]]
    ) -> bool:
        """
        Set up model group for a species in Blender.

        Args:
            species: Species name
            model_files: List of (identifier, file_path) tuples (LOD levels or tree IDs)

        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            return False

        success_count = 0

        for identifier, model_path in sorted(
            model_files, key=lambda x: self.LOD_ORDER.get(x[0], 999)
        ):
            # Create object name following conventions
            # For LOD files: Species_LOD_Level
            # For individual trees: Species_tree_id
            object_name = f"{species}_{identifier}"

            if self.import_model(model_path, object_name):
                success_count += 1

        return success_count > 0

    def import_model_with_twigs(self, model_path: Path, object_name: str, species_name: str) -> bool:
        """
        Import a model file and add twigs if the model has twig placement data.
        
        Args:
            model_path: Path to model file (USD only for now)
            object_name: Name to give the imported object
            species_name: Species name for twig selection
            
        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            return False
            
        # First import the base model
        if not self.import_model(model_path, object_name):
            return False
            
        # For USD files, we need to access the original Grove model data
        # This is a limitation - we would need the original Grove model object
        # to access face attributes for twig placement
        
        # For now, we'll log that twig instancing requires Grove model data
        logger.info(f"Model {object_name} imported successfully. Twig instancing requires Grove model data.")
        
        return True

    def export_fbx(self, output_path: Path, species: str) -> bool:
        """
        Export current scene as FBX.

        Args:
            output_path: Path for output FBX file
            species: Species name for metadata

        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            logger.error("Blender is not available for FBX export")
            return False

        try:
            # Ensure output directory exists
            output_path.parent.mkdir(parents=True, exist_ok=True)
            
            # FBX export settings optimized for game engines
            bpy.ops.export_scene.fbx(
                filepath=str(output_path),
                use_selection=False,  # Export all objects
                use_active_collection=False,
                global_scale=1.0,  # Scale already applied to objects
                apply_unit_scale=True,
                apply_scale_options="FBX_SCALE_NONE",
                use_space_transform=True,
                bake_space_transform=False,
                object_types={"MESH"},
                use_mesh_modifiers=True,
                use_mesh_modifiers_render=True,
                mesh_smooth_type="OFF",  # Preserve original normals
                use_subsurf=False,
                use_mesh_edges=False,
                use_tspace=False,
                use_triangles=False,  # Keep quads if possible
                use_custom_props=False,
                add_leaf_bones=False,
                primary_bone_axis="Y",
                secondary_bone_axis="X",
                use_armature_deform_only=False,
                armature_nodetype="NULL",
                bake_anim=False,
                path_mode="AUTO",
                embed_textures=False,
                batch_mode="OFF",
            )

            logger.info(f"Successfully exported FBX: {output_path}")
            return True

        except Exception as e:
            logger.error(f"Failed to export FBX {output_path}: {e}")
            return False

    def process_species(
        self, species: str, model_files: List[Tuple[str, Path]]
    ) -> bool:
        """
        Process a single species - combine models and export FBX.

        Args:
            species: Species name
            model_files: List of (identifier, file_path) tuples (LOD levels or tree IDs)

        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            return False

        # Clear scene
        self.clear_scene()

        # Import all model files for this species
        if not self.setup_lod_group(species, model_files):
            return False

        # Export as FBX
        output_path = self.output_dir / f"{species}_Models.fbx"
        return self.export_fbx(output_path, species)

    def process_species_with_grove_data(
        self, species: str, grove_models: List, lod_names: List[str]
    ) -> bool:
        """
        Process a single species with Grove model data for twig instancing.

        Args:
            species: Species name
            grove_models: List of Grove model objects with face attributes
            lod_names: List of LOD names corresponding to models

        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            return False

        # Clear scene
        self.clear_scene()

        # Import models and add twigs
        for model, lod_name in zip(grove_models, lod_names):
            object_name = f"{species}_{lod_name}"
            
            # Create mesh from Grove model data
            if self.create_mesh_from_grove_model(model, object_name):
                # Add twigs to this model
                self.instance_twigs_on_model(model, species)

        # Export as FBX
        output_path = self.output_dir / f"{species}_Models.fbx"
        return self.export_fbx(output_path, species)

    def create_mesh_from_grove_model(self, model, object_name: str) -> bool:
        """
        Create a Blender mesh from Grove model data.
        
        Args:
            model: Grove model object
            object_name: Name for the created object
            
        Returns:
            True if successful, False otherwise
        """
        if not BLENDER_AVAILABLE:
            return False
            
        try:
            # Create new mesh
            mesh = bpy.data.meshes.new(object_name)
            
            # Convert Grove vectors to Blender format
            vertices = [(point.x, point.y, point.z) for point in model.points]
            faces = [face for face in model.faces]
            
            # Create mesh from data
            mesh.from_pydata(vertices, [], faces)
            mesh.update()
            
            # Create object
            obj = bpy.data.objects.new(object_name, mesh)
            
            # Apply scale
            if self.scale_factor != 1.0:
                obj.scale = (self.scale_factor, self.scale_factor, self.scale_factor)
                
            # Link to scene
            bpy.context.collection.objects.link(obj)
            
            logger.debug(f"Created mesh {object_name} with {len(vertices)} vertices and {len(faces)} faces")
            return True
            
        except Exception as e:
            logger.error(f"Failed to create mesh from Grove model: {e}")
            return False

    def combine_all_lods(self) -> Dict[str, bool]:
        """
        Combine all LOD files into FBX files.

        Returns:
            Dictionary mapping species name to success status
        """
        if not BLENDER_AVAILABLE:
            return {}

        # Group files by species
        species_groups = self.group_lod_files()

        if not species_groups:
            return {}

        # Process each species
        results = {}
        for species, lod_files in species_groups.items():
            results[species] = self.process_species(species, lod_files)

        return results

    def combine_with_grove_data(self, forest_data) -> Dict[str, bool]:
        """
        Combine LOD files with Grove model data for twig instancing.

        Args:
            forest_data: List of (grove, species_name, tree_count) tuples

        Returns:
            Dictionary mapping species name to success status
        """
        if not BLENDER_AVAILABLE:
            return {}

        results = {}
        
        # Import Grove core to build models
        try:
            import sys
            sys.path.append(str(Path(__file__).parent.parent / "the_grove_22" / "modules"))
            import the_grove_22_core as gc
            from growpy.core.config import GrowPyConfig
        except ImportError as e:
            logger.error(f"Failed to import Grove core: {e}")
            return {}

        # Get LOD configurations
        lod_configs = GrowPyConfig.get_lod_configs()
        
        for grove, species_name, _ in forest_data:
            try:
                # Build models for all LOD levels
                grove_models = []
                lod_names = []
                
                for lod_name, lod_settings in lod_configs.items():
                    models = grove.build_models(lod_settings)
                    if models:
                        grove_models.extend(models)
                        lod_names.extend([f"{lod_name}_tree_{i:03d}" for i in range(len(models))])
                
                if grove_models:
                    results[species_name] = self.process_species_with_grove_data(
                        species_name, grove_models, lod_names
                    )
                else:
                    results[species_name] = False
                    
            except Exception as e:
                logger.error(f"Failed to process species {species_name}: {e}")
                results[species_name] = False

        return results

    def create_manifest(self, results: Dict[str, bool]):
        """
        Create a manifest file describing the exported FBX files.

        Args:
            results: Dictionary mapping species name to success status
        """
        manifest_path = self.output_dir / "lod_manifest.txt"

        with open(manifest_path, "w") as f:
            f.write("LOD FBX Export Manifest\n")
            f.write("=" * 50 + "\n\n")
            f.write(f"Generated from: {self.input_dir}\n")
            f.write(f"Output directory: {self.output_dir}\n")
            f.write(f"Scale factor: {self.scale_factor}\n\n")

            f.write("Exported FBX Files:\n")
            f.write("-" * 30 + "\n")

            successful = []
            failed = []

            for species, success in results.items():
                if success:
                    fbx_file = f"{species}_Models.fbx"
                    f.write(f"✓ {fbx_file}\n")
                    successful.append(species)
                else:
                    f.write(f"✗ {species} (failed)\n")
                    failed.append(species)

            f.write("\nSummary:\n")
            f.write(f"  Successful: {len(successful)}\n")
            f.write(f"  Failed: {len(failed)}\n")

            if failed:
                f.write("\nFailed species:\n")
                for species in failed:
                    f.write(f"  - {species}\n")


def main():
    """
    Main function for command-line usage.
    """
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Combine LOD model files into FBX with twig instancing for Unity"
    )
    parser.add_argument(
        "--input_dir", 
        type=Path, 
        required=True,
        help="Directory containing LOD model files (OBJ/USD)"
    )
    parser.add_argument(
        "--output_dir", 
        type=Path, 
        required=True,
        help="Directory to save combined FBX files"
    )
    parser.add_argument(
        "--twigs_dir", 
        type=Path, 
        help="Directory containing twig .blend files (auto-detect if not provided)"
    )
    parser.add_argument(
        "--scale_factor", 
        type=float, 
        default=1.0,
        help="Scale factor to apply to all meshes (default: 1.0)"
    )
    parser.add_argument(
        "--with_grove_data", 
        action="store_true",
        help="Use Grove model data for twig instancing (requires CSV forest data)"
    )
    parser.add_argument(
        "--forest_csv", 
        type=Path,
        help="CSV file with forest data (required if --with_grove_data)"
    )
    
    args = parser.parse_args()
    
    if not BLENDER_AVAILABLE:
        logger.error("Blender is not available. Please install bpy module.")
        return False
    
    # Initialize combiner
    combiner = LODCombiner(
        input_dir=args.input_dir,
        output_dir=args.output_dir,
        scale_factor=args.scale_factor,
        twigs_dir=args.twigs_dir
    )
    
    # Process models
    if args.with_grove_data:
        if not args.forest_csv:
            logger.error("--forest_csv is required when using --with_grove_data")
            return False
            
        # Load forest data and generate models with Grove
        try:
            from growpy.workflows.simulation import simulate_forest_from_csv
            
            logger.info(f"Loading forest data from {args.forest_csv}")
            forest_data = simulate_forest_from_csv(args.forest_csv)
            
            logger.info("Starting FBX export with twig instancing...")
            results = combiner.combine_with_grove_data(forest_data)
            
        except ImportError as e:
            logger.error(f"Failed to import growpy simulation: {e}")
            return False
        except Exception as e:
            logger.error(f"Failed to process forest data: {e}")
            return False
    else:
        # Standard LOD combining without twig instancing
        logger.info("Starting standard FBX export...")
        results = combiner.combine_all_lods()
    
    # Create manifest
    combiner.create_manifest(results)
    
    # Report results
    successful = sum(1 for success in results.values() if success)
    total = len(results)
    logger.info(f"Export completed: {successful}/{total} species successful")
    
    return successful > 0


if __name__ == "__main__":
    main()