"""
Generate UE Python scripts that create PVE Graphs from combined presets.

EXPERIMENTAL -- UE 5.7+ Procedural Vegetation Editor (PVE) plugin only.

Creates one ProceduralVegetation graph per species+scene directory. Each
graph's PresetLoader points at a combined preset whose Variants TMap holds
all height stages found in that directory. The graph wires one processing
chain (Gravity -> MeshBuilder -> FoliagePalette -> Output) per variant.

Directory layout expected::

    data/output/forest/<species>/<scene>/
        <prefix>_h03m_*_stems_unreal_pve.json
        <prefix>_h06m_*_stems_unreal_pve.json
        ...
        FoliageData.json

UE Python API used (UE 5.7+, Experimental):
- unreal.ProceduralVegetationFactory     - graph asset factory
- unreal.ProceduralVegetationPreset      - combined preset DataAsset
- unreal.ProceduralVegetationGraph       - PCG graph (inner object)
- unreal.PVPresetLoaderSettings          - preset loader node
- unreal.PVGravitySettings               - gravity node
- unreal.PVMeshBuilderSettings           - mesh builder node
- unreal.PVFoliagePaletteSettings        - foliage palette node
- unreal.PVOutputSettings                - output node
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)


PVE_RECIPE_SUFFIX = "_stems_unreal_pve.json"


_PVE_GRAPH_SCRIPT = '''\
"""
GrowPy PVE graph builder -- Auto-generated.

Creates combined ProceduralVegetationPreset assets (one per species+scene
directory) and wires ProceduralVegetation graphs with per-variant processing
chains.

Generated by: growpy.io.unreal.pve_graph_script
"""
import os
import json

import unreal


FOREST_ROOT = r"{forest_root}"
PRESET_PACKAGE_PATH = "{preset_package_path}"
GRAPH_PACKAGE_PATH = "{graph_package_path}"
FOLIAGE_FOLDER = "{foliage_folder}"
MATERIALS_FOLDER = "{materials_folder}"
TRUNK_MATERIAL_NAME = "{trunk_material_name}"

PVE_RECIPE_SUFFIX = "_stems_unreal_pve.json"


def _have_pve_classes():
    """Check that the Procedural Vegetation Editor plugin is available."""
    for cls_name in (
        "ProceduralVegetationPreset",
        "ProceduralVegetationFactory",
        "ProceduralVegetationGraph",
        "PVPresetLoaderSettings",
        "PVGravitySettings",
        "PVMeshBuilderSettings",
        "PVBoneReductionSettings",
        "PVFoliagePaletteSettings",
        "PVOutputSettings",
    ):
        if not hasattr(unreal, cls_name):
            return False
    return True


def _make_directory_path(path_str):
    dp = unreal.DirectoryPath()
    dp.path = path_str
    return dp


def _ensure_foliage_data(json_dir):
    """Create a minimal FoliageData.json if missing."""
    foliage_path = os.path.join(json_dir, "FoliageData.json")
    if os.path.isfile(foliage_path):
        return
    with open(foliage_path, "w") as f:
        json.dump({{"Variations": []}}, f, indent=2)
    unreal.log("[PVE-G] Created FoliageData.json in %s" % json_dir)


def _discover_recipe_dirs(forest_root):
    """Find directories containing PVE recipe files.

    Returns a dict mapping directory path -> list of recipe basenames
    (without the .json extension, used as variant names by UpdateDataAsset).
    """
    recipe_dirs = {{}}
    for dirpath, _dirnames, filenames in os.walk(forest_root):
        variants = []
        for fname in sorted(filenames):
            if fname.endswith(PVE_RECIPE_SUFFIX):
                variants.append(os.path.splitext(fname)[0])
        if variants:
            recipe_dirs[dirpath.replace("\\\\", "/")] = variants
    return recipe_dirs


def _dir_to_asset_name(json_dir, forest_root):
    """Derive a clean asset name from the directory relative path.

    Example: european_beech/competition -> European_Beech_competition
    """
    rel = os.path.relpath(json_dir, forest_root).replace("\\\\", "/")
    parts = rel.split("/")
    # Convert to PascalCase-ish: European_Beech_competition
    name = "_".join(parts)
    # Capitalize each segment separated by underscores
    segments = name.split("_")
    segments = [s.capitalize() for s in segments]
    return "_".join(segments)


def _create_combined_preset(asset_name, package_path, json_dir,
                           foliage_folder="", materials_folder="",
                           trunk_material_name=""):
    """Create or refresh a combined preset pointing at a directory."""
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    full_path = "%s/%s" % (package_path, asset_name)

    if unreal.EditorAssetLibrary.does_asset_exist(full_path):
        asset = unreal.EditorAssetLibrary.load_asset(full_path)
        if asset is not None:
            _set_preset_properties(asset, json_dir, foliage_folder,
                                   materials_folder, trunk_material_name)
            try:
                asset.call_method("UpdateDataAsset")
                unreal.EditorAssetLibrary.save_loaded_asset(asset)
                unreal.log("[PVE-G] Refreshed preset: %s" % full_path)
            except Exception as _e:
                unreal.log_warning(
                    "[PVE-G] UpdateDataAsset failed on %s: %s" % (full_path, _e)
                )
        return asset

    asset = asset_tools.create_asset(
        asset_name=asset_name,
        package_path=package_path,
        asset_class=unreal.ProceduralVegetationPreset,
        factory=None,
    )
    if asset is None:
        unreal.log_warning("[PVE-G] Failed to create preset: %s" % asset_name)
        return None

    _set_preset_properties(asset, json_dir, foliage_folder,
                           materials_folder, trunk_material_name)
    unreal.EditorAssetLibrary.save_loaded_asset(asset)

    try:
        asset.call_method("UpdateDataAsset")
        unreal.EditorAssetLibrary.save_loaded_asset(asset)
        unreal.log("[PVE-G] Created preset: %s (%s)" % (asset_name, json_dir))
    except Exception as _e:
        unreal.log_warning(
            "[PVE-G] UpdateDataAsset failed for %s: %s" % (asset_name, _e)
        )

    return asset


def _set_preset_properties(asset, json_dir, foliage_folder, materials_folder,
                           trunk_material_name):
    """Set directory and material properties on a preset asset."""
    try:
        asset.set_editor_property("json_directory_path", _make_directory_path(json_dir))
    except Exception as _e:
        unreal.log_warning("[PVE-G] json_directory_path set failed: %s" % _e)
    try:
        asset.set_editor_property("override_folder_paths", True)
        if foliage_folder:
            asset.set_editor_property("foliage_folder",
                                      _make_directory_path(foliage_folder))
        if materials_folder:
            asset.set_editor_property("materials_folder",
                                      _make_directory_path(materials_folder))
    except Exception as _e:
        unreal.log_warning("[PVE-G] folder path set failed: %s" % _e)
    try:
        if trunk_material_name:
            asset.set_editor_property("trunk_material_name", trunk_material_name)
    except Exception as _e:
        unreal.log_warning("[PVE-G] trunk_material_name set failed: %s" % _e)


def _create_pve_graph(graph_name, graph_package, preset, variant_names):
    """Create a PVE graph with one processing chain per variant."""
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    full_path = "%s/%s" % (graph_package, graph_name)

    if unreal.EditorAssetLibrary.does_asset_exist(full_path):
        unreal.log("[PVE-G] Deleting existing graph for rebuild: %s" % full_path)
        unreal.EditorAssetLibrary.delete_asset(full_path)

    factory = unreal.ProceduralVegetationFactory()
    graph_asset = asset_tools.create_asset(
        asset_name=graph_name,
        package_path=graph_package,
        asset_class=None,
        factory=factory,
    )
    if graph_asset is None:
        unreal.log_warning("[PVE-G] Failed to create graph: %s" % graph_name)
        return None

    # Access inner ProceduralVegetationGraph via sub-object path
    graph_obj_path = "%s.%s:ProceduralVegetationGraph" % (full_path, graph_name)
    graph = unreal.load_object(None, graph_obj_path)
    if graph is None:
        unreal.log_warning("[PVE-G] Could not find inner graph: %s" % graph_obj_path)
        return graph_asset

    # Add PresetLoader node
    loader_settings = unreal.PVPresetLoaderSettings()
    loader_settings.set_editor_property("preset", preset)
    loader_node, _ = graph.add_node_copy(loader_settings)

    # Create one chain per variant:
    # PresetLoader -> Gravity -> MeshBuilder -> BoneReduction -> FoliagePalette -> Output
    for i, vname in enumerate(variant_names):
        grav_node, _ = graph.add_node_copy(unreal.PVGravitySettings())
        mesh_node, _ = graph.add_node_copy(unreal.PVMeshBuilderSettings())
        bone_node, _ = graph.add_node_copy(unreal.PVBoneReductionSettings())
        foliage_node, _ = graph.add_node_copy(unreal.PVFoliagePaletteSettings())
        output_node, output_settings = graph.add_node_copy(unreal.PVOutputSettings())

        # Set output node title to variant name for clarity
        try:
            output_node.set_editor_property("node_title", vname)
        except Exception:
            pass

        # Wire the chain
        graph.add_edge(loader_node, vname, grav_node, "In")
        graph.add_edge(grav_node, "Out", mesh_node, "In")
        graph.add_edge(mesh_node, "Out", bone_node, "In")
        graph.add_edge(bone_node, "Out", foliage_node, "In")
        graph.add_edge(foliage_node, "Out", output_node, "In")

    # Notify graph editor to refresh
    try:
        graph.call_method("ForceNotificationForEditor")
    except Exception:
        pass

    unreal.EditorAssetLibrary.save_loaded_asset(graph_asset)
    unreal.log(
        "[PVE-G] Created graph %s with %d variant chain(s)"
        % (graph_name, len(variant_names))
    )
    return graph_asset


def main():
    if not _have_pve_classes():
        unreal.log_error(
            "[PVE-G] Procedural Vegetation Editor plugin not enabled or "
            "UE version < 5.7. Aborting."
        )
        return

    if not os.path.isdir(FOREST_ROOT):
        unreal.log_error("[PVE-G] Forest root does not exist: %s" % FOREST_ROOT)
        return

    recipe_dirs = _discover_recipe_dirs(FOREST_ROOT)
    if not recipe_dirs:
        unreal.log_warning(
            "[PVE-G] No *%s files found under %s" % (PVE_RECIPE_SUFFIX, FOREST_ROOT)
        )
        return

    unreal.log(
        "[PVE-G] Found %d species/scene directory(ies)" % len(recipe_dirs)
    )

    for json_dir, variant_names in sorted(recipe_dirs.items()):
        _ensure_foliage_data(json_dir)

        # Derive asset names from directory path
        base_name = _dir_to_asset_name(json_dir, FOREST_ROOT)
        preset_name = "PVE_%s" % base_name
        graph_name = "PVG_%s" % base_name

        unreal.log(
            "[PVE-G] %s: %d variant(s) -> %s"
            % (preset_name, len(variant_names), graph_name)
        )

        # Create combined preset
        preset = _create_combined_preset(
            preset_name, PRESET_PACKAGE_PATH, json_dir,
            foliage_folder=FOLIAGE_FOLDER,
            materials_folder=MATERIALS_FOLDER,
            trunk_material_name=TRUNK_MATERIAL_NAME,
        )
        if preset is None:
            continue

        # Create graph
        _create_pve_graph(graph_name, GRAPH_PACKAGE_PATH, preset, variant_names)

    unreal.log("[PVE-G] Done.")


main()
'''


def generate_pve_graph_script(
    output_dir: Path,
    forest_root: Path,
    preset_package_path: str = "/Game/Assets/TheGrove/PVE",
    graph_package_path: str = "/Game/Assets/TheGrove/PVE/Graphs",
    foliage_folder: str = "/Game/Assets/TheGrove/PVE/Foliage",
    materials_folder: str = "/Game/Assets/TheGrove/PVE/Materials",
    trunk_material_name: str = "",
) -> Path:
    """Write a UE Python script that creates combined PVE presets and graphs.

    Args:
        output_dir: Where to write the .py script.
        forest_root: Root of the growpy forest export.
        preset_package_path: UE Content Browser path for combined presets.
        graph_package_path: UE Content Browser path for PVE graphs.
        foliage_folder: UE Content Browser path for PVE foliage meshes.
        materials_folder: UE Content Browser path for PVE materials.
        trunk_material_name: Trunk material name for bark texture.

    Returns:
        Path to the written script.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    script_path = output_dir / "growpy_pve_graph_builder.py"

    forest_root_str = str(forest_root.resolve()).replace("\\", "/")

    body = _PVE_GRAPH_SCRIPT.format(
        forest_root=forest_root_str,
        preset_package_path=preset_package_path,
        graph_package_path=graph_package_path,
        foliage_folder=foliage_folder,
        materials_folder=materials_folder,
        trunk_material_name=trunk_material_name,
    )

    script_path.write_text(body, encoding="utf-8")
    logger.info("Generated PVE graph builder script: %s", script_path)
    return script_path
