"""
Generate UE Python scripts that create PVE Graphs from combined presets.

EXPERIMENTAL -- UE 5.7+ Procedural Vegetation Editor (PVE) plugin only.

Creates one ProceduralVegetation graph per species+scene directory. Each
graph's PresetLoader points at a combined preset whose Variants TMap holds
all height stages found in that directory. The graph wires one processing
chain per variant following the Epic PVE tutorial node order:

    PresetLoader -> Curve -> Gravity -> Scale -> RemoveBranches ->
    MeshBuilder -> BoneReduction -> FoliagePalette ->
    FoliageDistributor -> Output

Nodes are positioned in a row-per-variant layout to avoid overlap.

Directory layout expected::

    data/output/forest/<species>/<scene>/
        <prefix>_h03m_*_stems_unreal_pve.json
        <prefix>_h06m_*_stems_unreal_pve.json
        ...
        FoliageData.json

UE Python API used (UE 5.7+, Experimental):
- unreal.ProceduralVegetationFactory     - graph asset factory
- unreal.ProceduralVegetationPreset      - combined preset DataAsset
- unreal.ProceduralVegetationGraph       - PCG graph (inner object)
- unreal.PVPresetLoaderSettings          - preset loader node
- unreal.PVCurveSettings                 - curve node
- unreal.PVGravitySettings               - gravity node
- unreal.PVScaleSettings                 - scale node
- unreal.PVRemoveBranchesSettings        - remove branches node
- unreal.PVMeshBuilderSettings           - mesh builder node
- unreal.PVBoneReductionSettings         - bone reduction node
- unreal.PVFoliagePaletteSettings        - foliage palette node
- unreal.PVFoliageDistributorSettings    - foliage distributor node
- unreal.PVOutputSettings                - output node
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)


PVE_RECIPE_SUFFIX = "_stems_unreal_pve.json"


_PVE_GRAPH_SCRIPT = '''\
"""
GrowPy PVE graph builder -- Auto-generated.

Creates combined ProceduralVegetationPreset assets (one per species+scene
directory) and wires ProceduralVegetation graphs with per-variant processing
chains. Presets and graphs are placed alongside tree assemblies.

Generated by: growpy.io.unreal.pve_graph_script
"""
import os
import json

import unreal


FOREST_ROOT = r"{forest_root}"
IMPORT_BASE = "{import_base}"
SPECIES_TWIG_MAP = {species_twig_map}

PVE_RECIPE_SUFFIX = "_stems_unreal_pve.json"


def _have_pve_classes():
    """Check that the Procedural Vegetation Editor plugin is available."""
    for cls_name in (
        "ProceduralVegetationPreset",
        "ProceduralVegetationFactory",
        "ProceduralVegetationGraph",
        "PVPresetLoaderSettings",
        "PVOutputSettings",
    ):
        if not hasattr(unreal, cls_name):
            return False
    return True


def _make_directory_path(path_str):
    dp = unreal.DirectoryPath()
    dp.path = path_str
    return dp


NODE_X_SPACING = 350
NODE_Y_SPACING = 250

CHAIN_NODE_TYPES = [
    ("PVCurveSettings", "Curve"),
    ("PVGravitySettings", "Gravity"),
    ("PVScaleSettings", "Scale"),
    ("PVRemoveBranchesSettings", "RemoveBranches"),
    ("PVMeshBuilderSettings", "MeshBuilder"),
    ("PVBoneReductionSettings", "BoneReduction"),
    ("PVFoliagePaletteSettings", "FoliagePalette"),
    ("PVFoliageDistributorSettings", "FoliageDistributor"),
    ("PVOutputSettings", "Output"),
]


def _position_node(node, x, y):
    """Set node position in the graph editor (PCGNode API)."""
    try:
        node.set_node_position(int(x), int(y))
    except Exception:
        pass


def _ensure_foliage_data(json_dir):
    """Verify FoliageData.json exists (generated by pve_foliage_data.py)."""
    foliage_path = os.path.join(json_dir, "FoliageData.json")
    if not os.path.isfile(foliage_path):
        unreal.log_warning(
            "[PVE-G] FoliageData.json missing in %s "
            "-- run generate_all_foliage_data() first" % json_dir
        )


def _discover_recipe_dirs(forest_root):
    """Find directories containing PVE recipe files.

    Returns a dict mapping directory path -> list of recipe basenames
    (without the .json extension, used as variant names by UpdateDataAsset).
    """
    recipe_dirs = {{}}
    for dirpath, _dirnames, filenames in os.walk(forest_root):
        variants = []
        for fname in sorted(filenames):
            if fname.endswith(PVE_RECIPE_SUFFIX):
                variants.append(os.path.splitext(fname)[0])
        if variants:
            recipe_dirs[dirpath.replace("\\\\", "/")] = variants
    return recipe_dirs


def _dir_to_asset_name(json_dir, forest_root):
    """Derive a clean asset name from the directory relative path.

    Example: european_beech/competition -> European_Beech_Competition
    """
    rel = os.path.relpath(json_dir, forest_root).replace("\\\\", "/")
    parts = rel.split("/")
    name = "_".join(parts)
    segments = name.split("_")
    segments = [s.capitalize() for s in segments]
    return "_".join(segments)


def _derive_dir_paths(json_dir):
    """Derive UE foliage, materials, and trunk paths for a recipe directory.

    Returns (package_path, foliage_folder, materials_folder, trunk_material_name).
    """
    rel = os.path.relpath(json_dir, FOREST_ROOT).replace("\\\\", "/")
    parts = rel.split("/")
    species = parts[0] if parts else ""

    package_path = IMPORT_BASE + "/" + rel

    # Materials folder: use the first assembly found in the dir
    # (combined presets span all heights, so just pick a representative)
    materials_folder = ""
    for fname in sorted(os.listdir(json_dir)):
        if fname.endswith(PVE_RECIPE_SUFFIX):
            stem = fname[:-len(PVE_RECIPE_SUFFIX)]
            assembly_name = stem + "_assembly"
            materials_folder = package_path + "/" + assembly_name + "/Materials"
            break

    twig_inst = SPECIES_TWIG_MAP.get(
        species, species + "_twigs_combined_skeletal"
    )
    foliage_folder = IMPORT_BASE + "/Instances/" + twig_inst + "/SkeletalMeshes"

    trunk_material_name = "MI_" + species + "_bark"

    return package_path, foliage_folder, materials_folder, trunk_material_name


def _create_combined_preset(asset_name, package_path, json_dir,
                           foliage_folder="", materials_folder="",
                           trunk_material_name=""):
    """Create or refresh a combined preset pointing at a directory."""
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    full_path = "%s/%s" % (package_path, asset_name)

    if unreal.EditorAssetLibrary.does_asset_exist(full_path):
        asset = unreal.EditorAssetLibrary.load_asset(full_path)
        if asset is not None:
            _set_preset_properties(asset, json_dir, foliage_folder,
                                   materials_folder, trunk_material_name)
            try:
                asset.call_method("UpdateDataAsset")
                unreal.EditorAssetLibrary.save_loaded_asset(asset)
                unreal.log("[PVE-G] Refreshed preset: %s" % full_path)
            except Exception as _e:
                unreal.log_warning(
                    "[PVE-G] UpdateDataAsset failed on %s: %s" % (full_path, _e)
                )
        return asset

    asset = asset_tools.create_asset(
        asset_name=asset_name,
        package_path=package_path,
        asset_class=unreal.ProceduralVegetationPreset,
        factory=None,
    )
    if asset is None:
        unreal.log_warning("[PVE-G] Failed to create preset: %s" % asset_name)
        return None

    _set_preset_properties(asset, json_dir, foliage_folder,
                           materials_folder, trunk_material_name)
    unreal.EditorAssetLibrary.save_loaded_asset(asset)

    try:
        asset.call_method("UpdateDataAsset")
        unreal.EditorAssetLibrary.save_loaded_asset(asset)
        unreal.log("[PVE-G] Created preset: %s (%s)" % (asset_name, json_dir))
    except Exception as _e:
        unreal.log_warning(
            "[PVE-G] UpdateDataAsset failed for %s: %s" % (asset_name, _e)
        )

    return asset


def _set_preset_properties(asset, json_dir, foliage_folder, materials_folder,
                           trunk_material_name):
    """Set directory and material properties on a preset asset."""
    try:
        asset.set_editor_property("json_directory_path", _make_directory_path(json_dir))
    except Exception as _e:
        unreal.log_warning("[PVE-G] json_directory_path set failed: %s" % _e)
    try:
        asset.set_editor_property("override_folder_paths", True)
        if foliage_folder:
            asset.set_editor_property("foliage_folder",
                                      _make_directory_path(foliage_folder))
        if materials_folder:
            asset.set_editor_property("materials_folder",
                                      _make_directory_path(materials_folder))
    except Exception as _e:
        unreal.log_warning("[PVE-G] folder path set failed: %s" % _e)
    try:
        if trunk_material_name:
            asset.set_editor_property("trunk_material_name", trunk_material_name)
    except Exception as _e:
        unreal.log_warning("[PVE-G] trunk_material_name set failed: %s" % _e)


def _patch_foliage_meshes(asset, foliage_folder):
    """Force-set foliage_meshes on preset variations via import_text.

    UpdateDataAsset creates variation slots from FoliageData.json but cannot
    resolve SkeletalMesh assets because UE USD import adds an SK_ prefix and
    places them in a SkeletalMeshes/ subfolder. This function reads
    pre-computed AssetPath entries from FoliageData.json (written by
    pve_foliage_data.py) and forces the references via import_text.

    Falls back to constructing paths from foliage_folder + SK_ prefix if
    AssetPath entries are not present (backward compatibility).
    """
    variations = asset.get_editor_property("preset_variations")
    if not variations:
        return

    patched = 0
    for var in variations:
        # Always attempt patch: UpdateDataAsset may leave foliage_meshes empty
        # for species that use shared twigs (e.g. Norway spruce -> pacific
        # silver fir), because the PVE recipe references twig names that don't
        # match the species name and UE can't resolve them.

        et = var.export_text()
        foliage_path = os.path.join(
            asset.get_editor_property("json_directory_path").path,
            "FoliageData.json",
        )
        if not os.path.isfile(foliage_path):
            continue

        with open(foliage_path, "r") as _f:
            foliage_data = json.load(_f)

        var_name = var.get_editor_property("name") if hasattr(var, "name") else ""
        # Try to get variation name from export text
        if not var_name and 'Name="' in et:
            var_name = et.split('Name="')[1].split('"')[0]

        # Find matching variation in FoliageData
        matched_entries = []
        for fv in foliage_data.get("Variations", []):
            fv_name = fv.get("name", "")
            if fv_name == var_name or not matched_entries:
                matched_entries = fv.get("Data", [])
                if fv_name == var_name:
                    break

        if not matched_entries:
            continue

        # Build full asset paths -- prefer pre-computed AssetPath from
        # pve_foliage_data.py, fall back to SK_ prefix construction.
        mesh_refs = []
        for entry in matched_entries:
            asset_path = entry.get("AssetPath")
            if asset_path:
                mesh_refs.append(asset_path)
            else:
                tn = entry.get("Name", "")
                if tn:
                    sk_name = tn if tn.startswith("SK_") else "SK_" + tn
                    mesh_refs.append(
                        "%s/%s.%s" % (foliage_folder, sk_name, sk_name)
                    )

        if not mesh_refs:
            continue

        # Use import_text to force foliage mesh references
        mesh_csv = ",".join('"%s"' % r for r in mesh_refs)
        import_str = "(FoliageMeshes=(%s))" % mesh_csv
        try:
            ok = var.import_text(import_str)
            if ok:
                patched += 1
        except Exception as _e:
            unreal.log_warning(
                "[PVE-G] import_text failed for variation %s: %s" % (var_name, _e)
            )

    if patched:
        unreal.EditorAssetLibrary.save_loaded_asset(asset)
        unreal.log("[PVE-G] Patched foliage_meshes on %d variation(s)" % patched)


def _create_pve_graph(graph_name, graph_package, preset, variant_names):
    """Create a PVE graph following the Epic tutorial node chain order.

    Per-variant chain (skips unavailable node types):
        Curve -> Gravity -> Scale -> RemoveBranches -> MeshBuilder ->
        BoneReduction -> FoliagePalette -> FoliageDistributor -> Output
    """
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    full_path = "%s/%s" % (graph_package, graph_name)

    if unreal.EditorAssetLibrary.does_asset_exist(full_path):
        unreal.log("[PVE-G] Removing existing graph: %s" % full_path)
        trash_path = "%s/%s_OLD" % (graph_package, graph_name)
        if unreal.EditorAssetLibrary.does_asset_exist(trash_path):
            unreal.EditorAssetLibrary.delete_asset(trash_path)
            unreal.SystemLibrary.collect_garbage()
        renamed = unreal.EditorAssetLibrary.rename_asset(full_path, trash_path)
        if renamed:
            unreal.EditorAssetLibrary.delete_asset(trash_path)
        else:
            unreal.EditorAssetLibrary.delete_asset(full_path)
        unreal.SystemLibrary.collect_garbage()

    factory = unreal.ProceduralVegetationFactory()
    graph_asset = asset_tools.create_asset(
        asset_name=graph_name,
        package_path=graph_package,
        asset_class=None,
        factory=factory,
    )
    if graph_asset is None:
        unreal.log_warning("[PVE-G] Failed to create graph: %s" % graph_name)
        return None

    graph_obj_path = "%s.%s:ProceduralVegetationGraph" % (full_path, graph_name)
    graph = unreal.load_object(None, graph_obj_path)
    if graph is None:
        unreal.log_warning("[PVE-G] Could not find inner graph: %s" % graph_obj_path)
        return graph_asset

    # Filter chain to node types available in this UE build
    available_chain = []
    for cls_name, label in CHAIN_NODE_TYPES:
        if hasattr(unreal, cls_name):
            available_chain.append((cls_name, label))
        else:
            unreal.log_warning(
                "[PVE-G] Node class %s not available, skipping" % cls_name
            )

    # PresetLoader positioned at left, centered vertically
    loader_settings = unreal.PVPresetLoaderSettings()
    loader_settings.set_editor_property("preset", preset)
    loader_node, _ = graph.add_node_copy(loader_settings)
    loader_y = (len(variant_names) - 1) * NODE_Y_SPACING // 2
    _position_node(loader_node, 0, loader_y)

    for i, vname in enumerate(variant_names):
        row_y = i * NODE_Y_SPACING
        prev_node = loader_node
        prev_pin = vname

        for j, (cls_name, label) in enumerate(available_chain):
            settings_cls = getattr(unreal, cls_name)
            node, settings = graph.add_node_copy(settings_cls())

            col_x = (j + 1) * NODE_X_SPACING
            _position_node(node, col_x, row_y)

            if cls_name == "PVOutputSettings":
                try:
                    node.set_editor_property("node_title", vname)
                except Exception:
                    pass

            graph.add_edge(prev_node, prev_pin, node, "In")
            prev_node = node
            prev_pin = "Out"

    try:
        graph.call_method("ForceNotificationForEditor")
    except Exception:
        pass

    unreal.EditorAssetLibrary.save_loaded_asset(graph_asset)
    unreal.log(
        "[PVE-G] Created graph %s with %d variant chain(s) x %d node(s) each"
        % (graph_name, len(variant_names), len(available_chain))
    )
    return graph_asset


def main():
    if not _have_pve_classes():
        unreal.log_error(
            "[PVE-G] Procedural Vegetation Editor plugin not enabled or "
            "UE version < 5.7. Aborting."
        )
        return

    if not os.path.isdir(FOREST_ROOT):
        unreal.log_error("[PVE-G] Forest root does not exist: %s" % FOREST_ROOT)
        return

    recipe_dirs = _discover_recipe_dirs(FOREST_ROOT)
    if not recipe_dirs:
        unreal.log_warning(
            "[PVE-G] No *%s files found under %s" % (PVE_RECIPE_SUFFIX, FOREST_ROOT)
        )
        return

    unreal.log(
        "[PVE-G] Found %d species/scene directory(ies)" % len(recipe_dirs)
    )

    for json_dir, variant_names in sorted(recipe_dirs.items()):
        _ensure_foliage_data(json_dir)

        base_name = _dir_to_asset_name(json_dir, FOREST_ROOT)
        preset_name = "PVE_%s" % base_name
        graph_name = "PVG_%s" % base_name

        package_path, foliage_folder, materials_folder, trunk_mat = (
            _derive_dir_paths(json_dir)
        )

        unreal.log(
            "[PVE-G] %s: %d variant(s) -> %s  [%s]"
            % (preset_name, len(variant_names), graph_name, package_path)
        )

        preset = _create_combined_preset(
            preset_name, package_path, json_dir,
            foliage_folder=foliage_folder,
            materials_folder=materials_folder,
            trunk_material_name=trunk_mat,
        )
        if preset is None:
            continue

        _patch_foliage_meshes(preset, foliage_folder)

        _create_pve_graph(graph_name, package_path, preset, variant_names)

    unreal.log("[PVE-G] Done.")


main()
'''


def generate_pve_graph_script(
    output_dir: Path,
    forest_root: Path,
    import_base: str = "/Game/Assets/TheGrove",
    species_twig_map: dict | None = None,
) -> Path:
    """Write a UE Python script that creates combined PVE presets and graphs.

    Presets and graphs are placed alongside tree assemblies under
    ``import_base/<species>/<scene>/``.

    Args:
        output_dir: Where to write the .py script.
        forest_root: Root of the growpy forest export.
        import_base: UE Content Browser base path for tree assets.
        species_twig_map: Maps species name to twig instance folder name.

    Returns:
        Path to the written script.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    script_path = output_dir / "growpy_pve_graph_builder.py"

    forest_root_str = str(forest_root.resolve()).replace("\\", "/")
    twig_map_repr = repr(species_twig_map or {})

    body = _PVE_GRAPH_SCRIPT.format(
        forest_root=forest_root_str,
        import_base=import_base,
        species_twig_map=twig_map_repr,
    )

    script_path.write_text(body, encoding="utf-8")
    logger.info("Generated PVE graph builder script: %s", script_path)
    return script_path
