"""
Generate UE Python scripts that create ProceduralVegetationPreset DataAssets
from growpy-emitted PVE JSON recipes.

EXPERIMENTAL — UE 5.7+ Procedural Vegetation Editor (PVE) plugin only.

The current production path exports skeletal-mesh USD assemblies that UE
imports directly. This module enables a complementary path: hand growpy's
PVE JSON recipes to PVE itself, which re-grows the tree inside UE using its
own simulation. Useful when you want PVE Graph nodes (Carve, Gravity,
Foliage Distributor, Bone Reduction) to act on growpy parameters.

Both paths can run from the same growpy export — they are not mutually
exclusive.

The runtime UE script walks the forest output directory recursively
because growpy writes per-tree PVE recipes at:

    data/output/forest/<species>/<scene>/<tree>/<file_prefix>_stems_unreal_pve.json

(see ``forest_stages.py``). One ``ProceduralVegetationPreset`` DataAsset is
created per recipe, named after the file basename with the
``_stems_unreal_pve.json`` suffix stripped.

UE Python API used (UE 5.7+, Experimental):
- unreal.ProceduralVegetationFactory   - DataAsset factory
- unreal.ProceduralVegetationPreset    - DataAsset holding JSON path + folders
- unreal.AssetToolsHelpers             - asset creation entry point
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Iterable, Optional

from growpy.utils.naming import camel_to_snake

logger = logging.getLogger(__name__)


PVE_RECIPE_SUFFIX = "_stems_unreal_pve.json"


def build_species_twig_map(lookup_csv: Optional[Path] = None) -> dict[str, str]:
    """Build a mapping from species name to UE twig instance folder name.

    Reads the tree_asset_lookup.csv ``Twig`` column, converts from CamelCase
    to the convention used by the UE twig import:
    ``{twig_base}_twigs_combined_skeletal``.

    Args:
        lookup_csv: Path to the CSV. If None, uses the standard lookup
            resolution from ``growpy.config.paths``.

    Returns:
        Dict mapping e.g. ``"norway_spruce"`` to
        ``"pacific_silver_fir_twigs_combined_skeletal"``.
    """
    if lookup_csv is not None:
        import pandas as pd

        df = pd.read_csv(lookup_csv)
    else:
        from growpy.config.paths import _get_lookup_table

        df = _get_lookup_table()

    twig_map: dict[str, str] = {}
    for _, row in df.iterrows():
        species = str(row.get("Standardized Name", "")).strip()
        twig_camel = str(row.get("Twig", "")).strip()
        if not species or not twig_camel or twig_camel in ("\u2014", "", "nan"):
            continue
        twig_snake = camel_to_snake(twig_camel)
        if twig_snake.endswith("_twig"):
            twig_base = twig_snake[: -len("_twig")]
        else:
            twig_base = twig_snake
        instance_name = f"{twig_base}_twigs_combined_skeletal"
        twig_map[species] = instance_name
    return twig_map


_PVE_PREAMBLE = '''"""
GrowPy PVE preset import - Auto-generated.

Walks FOREST_ROOT recursively for ``*{suffix}`` recipe files
and creates one ProceduralVegetationPreset DataAsset per recipe.
Each preset is placed alongside its tree assembly under IMPORT_BASE,
with foliage_folder and materials_folder derived per-tree.

Execute in Unreal Engine:
1. Right-click > "Execute Python File in Unreal"
2. Or: exec(open(r"{script_path}").read())

Requires the Procedural Vegetation Editor plugin to be enabled.
"""

import json
import os
import unreal


PVE_RECIPE_SUFFIX = "{suffix}"


def _have_pve_classes():
    return all(
        hasattr(unreal, _name) for _name in (
            "ProceduralVegetationFactory",
            "ProceduralVegetationPreset",
        )
    )


def _make_directory_path(path_str):
    """Build an unreal.DirectoryPath struct, tolerating constructor variants."""
    try:
        _dp = unreal.DirectoryPath()
        _dp.path = path_str
        return _dp
    except Exception:
        pass
    try:
        return unreal.DirectoryPath(path=path_str)
    except Exception as _e:
        unreal.log_warning(
            "[PVE] DirectoryPath construction failed for %s: %s" % (path_str, _e)
        )
        return None


def _ensure_foliage_data(json_dir):
    """Verify FoliageData.json exists (generated by pve_foliage_data.py)."""
    foliage_path = os.path.join(json_dir, "FoliageData.json")
    if not os.path.exists(foliage_path):
        unreal.log_warning(
            "[PVE] FoliageData.json missing in %s "
            "-- run generate_all_foliage_data() first" % json_dir
        )


def _derive_recipe_paths(json_dir, stem):
    """Derive UE package, foliage, and materials paths for a recipe.

    Returns (package_path, foliage_folder, materials_folder, trunk_material_name).
    """
    rel = os.path.relpath(json_dir, FOREST_ROOT).replace("\\\\", "/")
    parts = rel.split("/")
    species = parts[0] if parts else ""

    package_path = IMPORT_BASE + "/" + rel

    assembly_name = stem + "_assembly"
    materials_folder = package_path + "/" + assembly_name + "/Materials"

    twig_inst = SPECIES_TWIG_MAP.get(
        species, species + "_twigs_combined_skeletal"
    )
    foliage_folder = IMPORT_BASE + "/Instances/" + twig_inst + "/SkeletalMeshes"

    trunk_material_name = "MI_" + species + "_bark"

    return package_path, foliage_folder, materials_folder, trunk_material_name


def _create_pve_preset(asset_name, package_path, json_dir,
                       plant_profile_name, foliage_folder, materials_folder,
                       trunk_material_name=""):
    """Create one ProceduralVegetationPreset DataAsset.

    Returns the created asset or None on failure.
    """
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()

    # If asset already exists, re-trigger data loading.
    full_path = "%s/%s" % (package_path, asset_name)
    if unreal.EditorAssetLibrary.does_asset_exist(full_path):
        unreal.log("[PVE] Refreshing existing asset: %s" % full_path)
        asset = unreal.EditorAssetLibrary.load_asset(full_path)
        if asset is not None:
            try:
                asset.call_method('UpdateDataAsset')
                unreal.EditorAssetLibrary.save_loaded_asset(asset)
            except Exception as _e:
                unreal.log_warning(
                    "[PVE] UpdateDataAsset failed on existing %s: %s"
                    % (full_path, _e)
                )
        return asset

    try:
        asset = asset_tools.create_asset(
            asset_name=asset_name,
            package_path=package_path,
            asset_class=unreal.ProceduralVegetationPreset,
            factory=None,
        )
    except Exception as _e:
        unreal.log_warning(
            "[PVE] create_asset failed for %s: %s" % (asset_name, _e)
        )
        return None

    if asset is None:
        unreal.log_warning("[PVE] create_asset returned None for %s" % asset_name)
        return None

    _dp = _make_directory_path(json_dir)
    if _dp is not None:
        try:
            asset.set_editor_property("json_directory_path", _dp)
        except Exception as _e:
            unreal.log_warning("[PVE] json_directory_path set failed: %s" % _e)

    try:
        asset.set_editor_property("override_folder_paths", True)
        _ff = _make_directory_path(foliage_folder)
        if _ff is not None:
            asset.set_editor_property("foliage_folder", _ff)
        _mf = _make_directory_path(materials_folder)
        if _mf is not None:
            asset.set_editor_property("materials_folder", _mf)
    except Exception as _e:
        unreal.log_warning("[PVE] folder path set failed: %s" % _e)

    try:
        asset.set_editor_property("plant_profile_name", plant_profile_name)
        if trunk_material_name:
            asset.set_editor_property(
                "trunk_material_name", trunk_material_name
            )
        asset.set_editor_property("create_profile_data_asset", True)
    except Exception as _e:
        unreal.log_warning("[PVE] profile property set failed: %s" % _e)

    unreal.EditorAssetLibrary.save_loaded_asset(asset)

    # Load JSON data into the Variants TMap.
    try:
        asset.call_method('UpdateDataAsset')
        unreal.EditorAssetLibrary.save_loaded_asset(asset)
        unreal.log("[PVE] Loaded variant data for %s" % asset_name)
    except Exception as _e:
        unreal.log_warning(
            "[PVE] UpdateDataAsset failed for %s: %s" % (asset_name, _e)
        )

    return asset


def _patch_foliage_meshes(asset, foliage_folder):
    """Force-set foliage_meshes on preset variations via import_text.

    UpdateDataAsset creates variation slots from FoliageData.json but cannot
    resolve SkeletalMesh assets because UE USD import adds an SK_ prefix and
    places them in a SkeletalMeshes/ subfolder. This reads pre-computed
    AssetPath entries from FoliageData.json and forces the references.
    """
    variations = asset.get_editor_property("preset_variations")
    if not variations:
        return

    patched = 0
    for var in variations:
        # Always attempt patch: UpdateDataAsset may leave foliage_meshes empty
        # for species that use shared twigs (e.g. Norway spruce -> pacific
        # silver fir).

        foliage_path = os.path.join(
            asset.get_editor_property("json_directory_path").path,
            "FoliageData.json",
        )
        if not os.path.isfile(foliage_path):
            continue

        with open(foliage_path, "r") as _f:
            foliage_data = json.load(_f)

        var_name = ""
        et = var.export_text()
        if 'Name="' in et:
            var_name = et.split('Name="')[1].split('"')[0]

        matched_entries = []
        for fv in foliage_data.get("Variations", []):
            fv_name = fv.get("name", "")
            if fv_name == var_name or not matched_entries:
                matched_entries = fv.get("Data", [])
                if fv_name == var_name:
                    break

        if not matched_entries:
            continue

        mesh_refs = []
        for entry in matched_entries:
            asset_path = entry.get("AssetPath")
            if asset_path:
                mesh_refs.append(asset_path)
            else:
                tn = entry.get("Name", "")
                if tn:
                    sk_name = tn if tn.startswith("SK_") else "SK_" + tn
                    mesh_refs.append(
                        "%s/%s.%s" % (foliage_folder, sk_name, sk_name)
                    )

        if not mesh_refs:
            continue

        mesh_csv = ",".join('"%s"' % r for r in mesh_refs)
        import_str = "(FoliageMeshes=(%s))" % mesh_csv
        try:
            ok = var.import_text(import_str)
            if ok:
                patched += 1
        except Exception as _e:
            unreal.log_warning(
                "[PVE] import_text failed for variation %s: %s" % (var_name, _e)
            )

    if patched:
        unreal.EditorAssetLibrary.save_loaded_asset(asset)
        unreal.log("[PVE] Patched foliage_meshes on %d variation(s)" % patched)


def main():
    if not _have_pve_classes():
        unreal.log_error(
            "[PVE] Procedural Vegetation Editor plugin not enabled or "
            "UE version < 5.7. Aborting."
        )
        return

    if not os.path.isdir(FOREST_ROOT):
        unreal.log_error("[PVE] Forest root does not exist: %s" % FOREST_ROOT)
        return

    recipes = []
    for dirpath, _dirnames, filenames in os.walk(FOREST_ROOT):
        for fname in filenames:
            if fname.endswith(PVE_RECIPE_SUFFIX):
                recipes.append(os.path.join(dirpath, fname))
    recipes.sort()

    if not recipes:
        unreal.log_warning(
            "[PVE] No *%s files found under %s" % (PVE_RECIPE_SUFFIX, FOREST_ROOT)
        )
        return

    unreal.log("[PVE] Found %d PVE recipe(s) under %s" % (len(recipes), FOREST_ROOT))
    # Ensure FoliageData.json in each unique recipe directory.
    seen_dirs = set()
    for recipe_path in recipes:
        d = os.path.dirname(recipe_path).replace("\\\\", "/")
        if d not in seen_dirs:
            _ensure_foliage_data(d)
            seen_dirs.add(d)
    created = 0
    for recipe_path in recipes:
        json_dir = os.path.dirname(recipe_path).replace("\\\\", "/")
        basename = os.path.basename(recipe_path)
        stem = basename[: -len(PVE_RECIPE_SUFFIX)]
        asset_name = "PVE_" + stem
        package_path, foliage_folder, materials_folder, trunk_mat = (
            _derive_recipe_paths(json_dir, stem)
        )
        unreal.log(
            "[PVE] Creating %s -> %s" % (asset_name, package_path)
        )
        asset = _create_pve_preset(
            asset_name=asset_name,
            package_path=package_path,
            json_dir=json_dir,
            plant_profile_name=stem,
            foliage_folder=foliage_folder,
            materials_folder=materials_folder,
            trunk_material_name=trunk_mat,
        )
        if asset is not None:
            _patch_foliage_meshes(asset, foliage_folder)
        created += 1

    unreal.log(
        "[PVE] Created/refreshed %d preset(s) under %s"
        % (created, IMPORT_BASE)
    )


main()
'''


def generate_pve_preset_import_script(
    output_dir: Path,
    forest_root: Path,
    import_base: str = "/Game/Assets/TheGrove",
    species_twig_map: Optional[dict] = None,
) -> Path:
    """Write a UE Python script that creates ProceduralVegetationPreset assets.

    The generated script walks ``forest_root`` recursively at runtime
    (inside UE) for ``*_stems_unreal_pve.json`` recipe files written by
    growpy's per-tree exports. Each preset is placed alongside its tree
    assembly under ``import_base``, with foliage and materials folders
    derived per-tree from the directory structure.

    Args:
        output_dir: Where to write the .py script (typically the same
            ``unreal_scripts/`` folder as ``unreal_import_trees.py``).
        forest_root: Root of the growpy forest export. Must be an absolute
            path that UE can read; the script walks this folder recursively
            for per-tree PVE recipes.
        import_base: UE Content Browser base path for tree assets.
        species_twig_map: Maps species name (e.g. ``norway_spruce``) to
            the twig instance folder name (e.g.
            ``pacific_silver_fir_twigs_combined_skeletal``). Species not
            in the map fall back to ``{species}_twigs_combined_skeletal``.

    Returns:
        Path to the written script.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    script_path = output_dir / "growpy_pve_preset_import.py"

    # Resolve to absolute, forward-slash path for UE consumption.
    forest_root_str = str(forest_root.resolve()).replace("\\", "/")

    twig_map_repr = repr(species_twig_map or {})

    header = (
        f'FOREST_ROOT = r"{forest_root_str}"\n'
        f'IMPORT_BASE = "{import_base}"\n'
        f"SPECIES_TWIG_MAP = {twig_map_repr}\n\n"
    )

    body = _PVE_PREAMBLE.format(
        script_path=str(script_path).replace("\\", "/"),
        suffix=PVE_RECIPE_SUFFIX,
    )

    script_path.write_text(header + body, encoding="utf-8")
    logger.info("Generated PVE preset import script: %s", script_path)
    return script_path


def generate_pve_import_for_species(
    output_dir: Path,
    pve_json_paths: Iterable[Path],
    import_base: str = "/Game/Assets/TheGrove",
    species_twig_map: Optional[dict] = None,
) -> Optional[Path]:
    """Convenience: derive forest_root from a list of per-tree JSON paths.

    Picks the common ancestor directory of the supplied paths and forwards
    it to ``generate_pve_preset_import_script``. Useful when callers already
    have the recipe list materialised; otherwise call the main helper with
    the forest output directory directly.
    """
    paths = list(pve_json_paths)
    if not paths:
        return None
    abs_paths = [p.resolve() for p in paths]
    common = Path(os.path.commonpath([str(p) for p in abs_paths]))
    return generate_pve_preset_import_script(
        output_dir=output_dir,
        forest_root=common,
        import_base=import_base,
        species_twig_map=species_twig_map,
    )
