"""
Generate UE Python script that imports DynamicWind JSON data into skeletal meshes.

The Blueprint function ImportDynamicWindSkeletalDataFromFile opens a file dialog
and cannot be used for batch operations. This module generates a Python script
that replicates the import logic: it reads each wind JSON, maps joint names to
bone indices on the corresponding SkeletalMesh, and writes the DynamicWind data
directly via reflection.

The runtime UE script walks the forest output directory recursively for
``*_stems_unreal_wind.json`` files, locates the matching nanite assembly
SkeletalMesh in the Content Browser, and applies the wind simulation groups.

Wind JSON files are generated by ``wind_json.py`` during forest export and live
alongside each tree's USD files:

    data/output/forest/<species>/<scene>/<tree>/<prefix>_stems_unreal_wind.json
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

WIND_JSON_SUFFIX = "_stems_unreal_wind.json"

_WIND_IMPORT_PREAMBLE = '''"""
GrowPy DynamicWind import - Auto-generated.

Walks FOREST_ROOT recursively for ``*{suffix}`` files
and applies DynamicWind skeletal data to the corresponding
nanite assembly SkeletalMesh assets in the Content Browser.

Execute in Unreal Engine:
1. Right-click > "Execute Python File in Unreal"
2. Or: exec(open(r"{script_path}").read())

Requires the DynamicWind plugin to be enabled (Experimental).
"""

import json
import os
import unreal


WIND_JSON_SUFFIX = "{suffix}"


def _have_dynamic_wind():
    """Check whether DynamicWind classes are available."""
    # Try loading the module class descriptor
    try:
        _cls = unreal.load_class(
            None, "/Script/DynamicWind.DynamicWindSkeletalData"
        )
        if _cls is not None:
            return True
    except Exception:
        pass
    # Direct attribute check
    return hasattr(unreal, "DynamicWindSkeletalData")


def _find_assembly_mesh(json_dir, stem):
    """Locate the nanite assembly SkeletalMesh for a wind JSON file.

    Derives the UE asset path from the on-disk directory structure.
    UE USD importer places skeletal meshes under a SkeletalMeshes/ subfolder
    with the prim name: SK_{{species}}_nanite_assembly.

    Returns the loaded SkeletalMesh or None.
    """
    rel = os.path.relpath(json_dir, FOREST_ROOT).replace("\\\\", "/")

    # e.g. European_Beech_comp_h12m_d19cm_full_stems_unreal_wind
    #   -> European_Beech_comp_h12m_d19cm_full_assembly
    assembly_stem = stem.replace("_stems_unreal_wind", "") + "_assembly"

    package_path = IMPORT_BASE + "/" + rel

    # Derive species name from assembly_stem for the SK_ asset name.
    # Convention: {{Species}}_{{comp|open}}_h{{HH}}m_... -> species before _comp_/_open_
    species_part = ""
    for tag in ("_comp_", "_open_"):
        idx = assembly_stem.lower().find(tag)
        if idx > 0:
            species_part = assembly_stem[:idx].lower()
            break

    # Build candidate paths (most specific first).
    # UE USD importer places skeletal meshes in SkeletalMeshes/ subfolder.
    candidates = []
    if species_part:
        candidates.append(
            "%s/%s/SkeletalMeshes/SK_%s_nanite_assembly"
            % (package_path, assembly_stem, species_part)
        )
    candidates.extend([
        "%s/%s/SkeletalMeshes/SK_%s" % (
            package_path, assembly_stem, assembly_stem),
        "%s/%s/SK_%s" % (package_path, assembly_stem, assembly_stem),
        "%s/SK_%s" % (package_path, assembly_stem),
    ])

    for asset_path in candidates:
        if unreal.EditorAssetLibrary.does_asset_exist(asset_path):
            mesh = unreal.EditorAssetLibrary.load_asset(asset_path)
            if mesh is not None and isinstance(mesh, unreal.SkeletalMesh):
                return mesh

    # Fallback: search recursively under the assembly folder using
    # get_assets_by_path (compatible with UE 5.7+, unlike ARFilter).
    assembly_path = package_path + "/" + assembly_stem
    try:
        registry = unreal.AssetRegistryHelpers.get_asset_registry()
        all_assets = registry.get_assets_by_path(assembly_path, recursive=True)
        for asset_data in all_assets:
            name = str(asset_data.asset_name).lower()
            asset_class = ""
            try:
                asset_class = str(asset_data.asset_class_path.asset_name)
            except Exception:
                try:
                    asset_class = str(asset_data.asset_class)
                except Exception:
                    pass
            if "SkeletalMesh" not in asset_class:
                continue
            if "nanite_assembly" in name or "assembly" in name:
                mesh = asset_data.get_asset()
                if mesh is not None and isinstance(mesh, unreal.SkeletalMesh):
                    return mesh
    except Exception as _e:
        unreal.log_warning(
            "[Wind] Asset registry search failed for %s: %s"
            % (assembly_path, _e)
        )

    unreal.log_warning(
        "[Wind] Could not find assembly SkeletalMesh for %s" % stem
    )
    return None


def _get_bone_names(mesh):
    """Get ordered bone (joint) names from a SkeletalMesh."""
    try:
        skeleton = mesh.skeleton
        if skeleton is None:
            skeleton = mesh.get_editor_property("skeleton")
    except Exception:
        skeleton = None

    # Strategy 1: via Skeleton asset bone tree
    if skeleton is not None:
        try:
            bone_tree = skeleton.get_editor_property("bone_tree")
            if bone_tree:
                return [str(b.get_editor_property("name")) for b in bone_tree]
        except Exception:
            pass

    # Strategy 2: RefSkeleton from mesh
    try:
        ref_skel = mesh.get_editor_property("ref_skeleton")
        if ref_skel:
            info = ref_skel.get_editor_property("ref_bone_info")
            if info:
                return [str(b.get_editor_property("name")) for b in info]
    except Exception:
        pass

    # Strategy 3: AnimationBlueprintLibrary
    try:
        bone_names = unreal.AnimationLibrary.get_bone_names(mesh)
        if bone_names:
            return [str(n) for n in bone_names]
    except Exception:
        pass

    # Strategy 4: SkeletalMeshLibrary
    try:
        bone_names = unreal.SkeletalMeshLibrary.get_bone_names(mesh)
        if bone_names:
            return [str(n) for n in bone_names]
    except Exception:
        pass

    return []


def _map_joints_to_bones(joints_data, bone_names):
    """Map wind JSON joint names to skeleton bone indices.

    Joint names in the wind JSON use hierarchical paths like
    ``tree_root/branch_0/joint_1``. Bone names in the UE skeleton use
    the leaf token only (e.g. ``joint_1``).

    Returns a list of (bone_index, simulation_group_index) tuples.
    """
    # Build lookup: leaf bone name -> bone index
    bone_lookup = {{}}
    for idx, name in enumerate(bone_names):
        bone_lookup[name.lower()] = idx

    mappings = []
    unmatched = 0

    for joint in joints_data:
        joint_name = joint.get("JointName", "")
        group_idx = joint.get("SimulationGroupIndex", 0)

        # Try full name first (in case UE kept hierarchical names)
        full_clean = joint_name.replace("/", "_").lower()
        if full_clean in bone_lookup:
            mappings.append((bone_lookup[full_clean], group_idx))
            continue

        # Try leaf token (last path component)
        leaf = joint_name.rsplit("/", 1)[-1].lower()
        if leaf in bone_lookup:
            mappings.append((bone_lookup[leaf], group_idx))
            continue

        # Try the full hierarchical name as-is
        if joint_name.lower() in bone_lookup:
            mappings.append((bone_lookup[joint_name.lower()], group_idx))
            continue

        unmatched += 1

    if unmatched > 0:
        unreal.log_warning(
            "[Wind] %d/%d joints could not be mapped to skeleton bones"
            % (unmatched, len(joints_data))
        )

    return mappings


def _apply_wind_data_strategy_a(mesh, wind_data, bone_names):
    """Strategy A: Use DynamicWindSkeletalData class via load_class.

    Creates a DynamicWindSkeletalData object, populates it, and assigns
    it to the mesh's transform_provider_data property.
    """
    wind_cls = None
    for class_path in (
        "/Script/DynamicWind.DynamicWindSkeletalData",
        "/Script/DynamicWind.DynamicWindData",
    ):
        try:
            wind_cls = unreal.load_class(None, class_path)
            if wind_cls is not None:
                break
        except Exception:
            continue

    if wind_cls is None:
        return False

    try:
        wind_obj = unreal.new_object(wind_cls)
    except Exception:
        try:
            wind_obj = wind_cls()
        except Exception:
            return False

    if wind_obj is None:
        return False

    # Populate simulation groups
    sim_groups = wind_data.get("SimulationGroups", [])
    try:
        wind_obj.set_editor_property("num_simulation_groups", len(sim_groups))
    except Exception:
        pass

    for idx, sg in enumerate(sim_groups):
        for prop, key in [
            ("influence", "Influence"),
            ("min_influence", "MinInfluence"),
            ("max_influence", "MaxInfluence"),
            ("shift_top", "ShiftTop"),
            ("is_trunk_group", "bIsTrunkGroup"),
            ("use_dual_influence", "bUseDualInfluence"),
        ]:
            try:
                wind_obj.set_editor_property(
                    "%s_%d" % (prop, idx), sg.get(key, 0)
                )
            except Exception:
                pass

    try:
        wind_obj.set_editor_property(
            "is_ground_cover", wind_data.get("bIsGroundCover", False)
        )
    except Exception:
        pass

    try:
        wind_obj.set_editor_property(
            "gust_attenuation", wind_data.get("GustAttenuation", 0.0)
        )
    except Exception:
        pass

    # Map joints to bones
    mappings = _map_joints_to_bones(
        wind_data.get("Joints", []), bone_names
    )

    # Set per-bone group indices
    num_bones = len(bone_names)
    group_indices = [0] * num_bones
    for bone_idx, group_idx in mappings:
        if 0 <= bone_idx < num_bones:
            group_indices[bone_idx] = group_idx

    try:
        wind_obj.set_editor_property("bone_group_indices", group_indices)
    except Exception:
        pass

    try:
        wind_obj.set_editor_property(
            "joint_group_indices", group_indices
        )
    except Exception:
        pass

    # Attach to mesh
    attached = False
    for prop_name in (
        "dynamic_wind_skeletal_data",
        "dynamic_wind_data",
        "transform_provider_data",
        "transform_provider_datas",
    ):
        try:
            mesh.set_editor_property(prop_name, wind_obj)
            attached = True
            break
        except Exception:
            continue

    if not attached:
        # Try as array element
        for prop_name in (
            "transform_provider_datas",
            "transform_provider_data",
        ):
            try:
                existing = mesh.get_editor_property(prop_name)
                if isinstance(existing, (list, unreal.Array)):
                    existing.append(wind_obj)
                    mesh.set_editor_property(prop_name, existing)
                    attached = True
                    break
                else:
                    mesh.set_editor_property(prop_name, [wind_obj])
                    attached = True
                    break
            except Exception:
                continue

    return attached


def _apply_wind_data_strategy_b(mesh, wind_data, bone_names):
    """Strategy B: Call import method on mesh with JSON path.

    Some UE versions expose import methods directly on SkeletalMesh.
    """
    # Build a temp JSON path if needed
    for method_name in (
        "import_dynamic_wind_data",
        "import_dynamic_wind_skeletal_data",
        "ImportDynamicWindData",
        "ImportDynamicWindSkeletalData",
        "import_transform_provider_data",
    ):
        try:
            result = mesh.call_method(method_name, wind_data["_file_path"])
            return True
        except Exception:
            continue
    return False


def _apply_wind_data_strategy_c(mesh, wind_data, bone_names):
    """Strategy C: Use import_text to inject wind data via text serialization.

    SkeletalMesh properties can sometimes be set via UE's text import format.
    """
    mappings = _map_joints_to_bones(
        wind_data.get("Joints", []), bone_names
    )

    num_bones = len(bone_names)
    group_indices = [0] * num_bones
    for bone_idx, group_idx in mappings:
        if 0 <= bone_idx < num_bones:
            group_indices[bone_idx] = group_idx

    sim_groups = wind_data.get("SimulationGroups", [])

    # Build the struct text for import_text
    sg_entries = []
    for sg in sim_groups:
        sg_entries.append(
            "(bUseDualInfluence=%s,Influence=%f,MinInfluence=%f,"
            "MaxInfluence=%f,ShiftTop=%f,bIsTrunkGroup=%s)"
            % (
                "True" if sg.get("bUseDualInfluence", False) else "False",
                sg.get("Influence", 0.0),
                sg.get("MinInfluence", 0.0),
                sg.get("MaxInfluence", 0.0),
                sg.get("ShiftTop", 0.0),
                "True" if sg.get("bIsTrunkGroup", False) else "False",
            )
        )

    indices_str = ",".join(str(g) for g in group_indices)
    groups_str = ",".join(sg_entries)

    # Try setting as wind data struct
    import_str = (
        "(BoneGroupIndices=(%s),SimulationGroups=(%s),"
        "bIsGroundCover=%s,GustAttenuation=%f)"
        % (
            indices_str,
            groups_str,
            "True" if wind_data.get("bIsGroundCover", False) else "False",
            wind_data.get("GustAttenuation", 0.0),
        )
    )

    for prop_name in (
        "dynamic_wind_skeletal_data",
        "dynamic_wind_data",
    ):
        try:
            obj = mesh.get_editor_property(prop_name)
            if obj is not None:
                obj.import_text(import_str)
                mesh.set_editor_property(prop_name, obj)
                return True
        except Exception:
            continue

    return False


def _apply_wind_data_strategy_d(mesh, wind_data, bone_names):
    """Strategy D: Enumerate all mesh properties to find wind-related ones.

    Discovery fallback. Logs available wind properties for debugging.
    """
    found_props = []
    for prop_name in dir(mesh):
        prop_lower = prop_name.lower()
        if "wind" in prop_lower or "dynamic" in prop_lower:
            found_props.append(prop_name)

    if found_props:
        unreal.log(
            "[Wind] Discovery: mesh has wind-related attributes: %s"
            % ", ".join(found_props)
        )

    # Try get_editor_property for common wind property names
    for prop_name in (
        "dynamic_wind_skeletal_data",
        "dynamic_wind_data",
        "wind_data",
        "dynamic_wind",
        "transform_provider_data",
        "transform_provider_datas",
        "asset_user_data",
    ):
        try:
            val = mesh.get_editor_property(prop_name)
            unreal.log(
                "[Wind] Discovery: get_editor_property('%s') = %s (%s)"
                % (prop_name, val, type(val).__name__)
            )
        except Exception:
            pass

    return False


def _apply_wind_data(mesh, wind_data, label):
    """Apply DynamicWind data to a SkeletalMesh using multiple strategies."""
    bone_names = _get_bone_names(mesh)
    if not bone_names:
        unreal.log_warning(
            "[Wind] No bones found on %s -- cannot map wind joints" % label
        )
        return False

    joints = wind_data.get("Joints", [])
    unreal.log(
        "[Wind] %s: %d joints in JSON, %d bones in skeleton"
        % (label, len(joints), len(bone_names))
    )

    strategies = [
        ("A: DynamicWindSkeletalData class", _apply_wind_data_strategy_a),
        ("B: call_method import", _apply_wind_data_strategy_b),
        ("C: import_text serialization", _apply_wind_data_strategy_c),
        ("D: property discovery", _apply_wind_data_strategy_d),
    ]

    for name, fn in strategies:
        try:
            if fn(mesh, wind_data, bone_names):
                unreal.log("[Wind] Strategy %s succeeded for %s" % (name, label))
                return True
        except Exception as _e:
            unreal.log_warning(
                "[Wind] Strategy %s failed for %s: %s" % (name, label, _e)
            )

    unreal.log_warning(
        "[Wind] All strategies failed for %s. "
        "Run this script once and check the Output Log for discovery info "
        "to identify the correct API for your UE version." % label
    )
    return False


def main():
    if not os.path.isdir(FOREST_ROOT):
        unreal.log_error("[Wind] Forest root does not exist: %s" % FOREST_ROOT)
        return

    # Discover wind JSON files
    wind_files = []
    for dirpath, _dirnames, filenames in os.walk(FOREST_ROOT):
        for fname in filenames:
            if fname.endswith(WIND_JSON_SUFFIX):
                wind_files.append(os.path.join(dirpath, fname))
    wind_files.sort()

    if not wind_files:
        unreal.log_warning(
            "[Wind] No *%s files found under %s"
            % (WIND_JSON_SUFFIX, FOREST_ROOT)
        )
        return

    unreal.log(
        "[Wind] Found %d wind JSON file(s) under %s"
        % (len(wind_files), FOREST_ROOT)
    )

    # Report DynamicWind plugin availability
    has_dw = _have_dynamic_wind()
    unreal.log(
        "[Wind] DynamicWind classes available: %s" % has_dw
    )

    applied = 0
    failed = 0

    for wind_file in wind_files:
        json_dir = os.path.dirname(wind_file).replace("\\\\", "/")
        basename = os.path.basename(wind_file)
        stem = basename[: -len(".json")]

        # Read wind JSON
        try:
            with open(wind_file, "r") as f:
                wind_data = json.load(f)
        except Exception as _e:
            unreal.log_warning(
                "[Wind] Could not read %s: %s" % (basename, _e)
            )
            failed += 1
            continue

        # Store file path for strategy B
        wind_data["_file_path"] = wind_file.replace("\\\\", "/")

        # Find the matching SkeletalMesh
        mesh = _find_assembly_mesh(json_dir, stem)
        if mesh is None:
            failed += 1
            continue

        label = stem.replace("_stems_unreal_wind", "")
        unreal.log("[Wind] Applying wind data to %s" % label)

        if _apply_wind_data(mesh, wind_data, label):
            try:
                unreal.EditorAssetLibrary.save_loaded_asset(mesh)
            except Exception:
                pass
            applied += 1
        else:
            failed += 1

    unreal.log(
        "[Wind] Done: %d applied, %d failed out of %d total"
        % (applied, failed, len(wind_files))
    )


main()
'''


def generate_wind_import_script(
    output_dir: Path,
    forest_root: Path,
    import_base: str = "/Game/Assets/TheGrove",
) -> Path:
    """Write a UE Python script that imports DynamicWind data into skeletal meshes.

    The generated script walks ``forest_root`` at runtime (inside UE) for
    ``*_stems_unreal_wind.json`` files. For each, it locates the matching
    nanite assembly SkeletalMesh in the Content Browser and applies the
    wind simulation group data.

    Args:
        output_dir: Where to write the .py script (typically ``unreal_scripts/``).
        forest_root: Root of the growpy forest export (absolute path).
        import_base: UE Content Browser base path for tree assets.

    Returns:
        Path to the written script.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    script_path = output_dir / "growpy_wind_import.py"

    forest_root_str = str(forest_root.resolve()).replace("\\", "/")

    header = (
        f'FOREST_ROOT = r"{forest_root_str}"\n' f'IMPORT_BASE = "{import_base}"\n\n'
    )

    body = _WIND_IMPORT_PREAMBLE.format(
        script_path=str(script_path).replace("\\", "/"),
        suffix=WIND_JSON_SUFFIX,
    )

    script_path.write_text(header + body, encoding="utf-8")
    logger.info("Generated DynamicWind import script: %s", script_path)
    return script_path
