"""
Generate UE Python script that imports DynamicWind JSON data into skeletal meshes.

The Blueprint function ImportDynamicWindSkeletalDataFromFile opens a file dialog
and cannot be used for batch operations. This module generates a Python script
that attaches DynamicWindSkeletalData as AssetUserData on each SkeletalMesh and
populates SimulationGroups, bIsGroundCover, and GustAttenuation.

.. note::

    The per-bone joint-to-group mapping (``Joints`` in the wind JSON) is not
    exposed to the UE Python API.  SimulationGroups and scalar properties are
    set correctly; the runtime DynamicWind system may use the skeleton hierarchy
    to infer per-bone assignments, or the mapping can be applied manually via
    the editor's *Import DynamicWind Skeletal Data* button on each mesh.

Wind JSON files are generated by ``wind_json.py`` during forest export:

    data/output/forest/<species>/<scene>/<tree>/<prefix>_stems_unreal_wind.json
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

WIND_JSON_SUFFIX = "_stems_unreal_wind.json"

_WIND_IMPORT_PREAMBLE = '''"""
GrowPy DynamicWind import - Auto-generated.

Walks FOREST_ROOT recursively for ``*{suffix}`` files
and applies DynamicWind skeletal data to the corresponding
nanite assembly SkeletalMesh assets in the Content Browser.

Execute in Unreal Engine:
1. Right-click > "Execute Python File in Unreal"
2. Or: exec(open(r"{script_path}").read())

Requires the DynamicWind plugin to be enabled (Experimental).
"""

import json
import os
import unreal


WIND_JSON_SUFFIX = "{suffix}"


def _have_dynamic_wind():
    """Check whether DynamicWind classes are available."""
    try:
        _cls = unreal.load_class(
            None, "/Script/DynamicWind.DynamicWindSkeletalData"
        )
        if _cls is not None:
            return True
    except Exception:
        pass
    return hasattr(unreal, "DynamicWindSkeletalData")


def _find_assembly_mesh(json_dir, stem):
    """Locate the nanite assembly SkeletalMesh for a wind JSON file.

    Derives the UE asset path from the on-disk directory structure.
    UE USD importer places skeletal meshes under a SkeletalMeshes/ subfolder
    with the prim name: SK_{{species}}_nanite_assembly.

    Returns the loaded SkeletalMesh or None.
    """
    rel = os.path.relpath(json_dir, FOREST_ROOT).replace("\\\\", "/")

    # e.g. European_Beech_comp_h12m_d19cm_full_stems_unreal_wind
    #   -> European_Beech_comp_h12m_d19cm_full_assembly
    assembly_stem = stem.replace("_stems_unreal_wind", "") + "_assembly"

    package_path = IMPORT_BASE + "/" + rel

    # Derive species name from assembly_stem for the SK_ asset name.
    # Convention: {{Species}}_{{comp|open}}_h{{HH}}m_... -> species before _comp_/_open_
    species_part = ""
    for tag in ("_comp_", "_open_"):
        idx = assembly_stem.lower().find(tag)
        if idx > 0:
            species_part = assembly_stem[:idx].lower()
            break

    # Build candidate paths (most specific first).
    candidates = []
    if species_part:
        candidates.append(
            "%s/%s/SkeletalMeshes/SK_%s_nanite_assembly"
            % (package_path, assembly_stem, species_part)
        )
    candidates.extend([
        "%s/%s/SkeletalMeshes/SK_%s" % (
            package_path, assembly_stem, assembly_stem),
        "%s/%s/SK_%s" % (package_path, assembly_stem, assembly_stem),
        "%s/SK_%s" % (package_path, assembly_stem),
    ])

    for asset_path in candidates:
        if unreal.EditorAssetLibrary.does_asset_exist(asset_path):
            mesh = unreal.EditorAssetLibrary.load_asset(asset_path)
            if mesh is not None and isinstance(mesh, unreal.SkeletalMesh):
                return mesh

    # Fallback: search recursively under the assembly folder.
    assembly_path = package_path + "/" + assembly_stem
    try:
        registry = unreal.AssetRegistryHelpers.get_asset_registry()
        all_assets = registry.get_assets_by_path(assembly_path, recursive=True)
        for asset_data in all_assets:
            name = str(asset_data.asset_name).lower()
            asset_class = ""
            try:
                asset_class = str(asset_data.asset_class_path.asset_name)
            except Exception:
                try:
                    asset_class = str(asset_data.asset_class)
                except Exception:
                    pass
            if "SkeletalMesh" not in asset_class:
                continue
            if "nanite_assembly" in name or "assembly" in name:
                mesh = asset_data.get_asset()
                if mesh is not None and isinstance(mesh, unreal.SkeletalMesh):
                    return mesh
    except Exception as _e:
        unreal.log_warning(
            "[Wind] Asset registry search failed for %s: %s"
            % (assembly_path, _e)
        )

    unreal.log_warning(
        "[Wind] Could not find assembly SkeletalMesh for %s" % stem
    )
    return None


def _apply_wind_data(mesh, wind_data, label):
    """Attach DynamicWindSkeletalData to mesh and populate wind properties.

    Creates or retrieves the DynamicWindSkeletalData AssetUserData object,
    then sets SimulationGroups, bIsGroundCover, and GustAttenuation from
    the wind JSON.

    The per-bone joint mapping (Joints) is not exposed to the UE Python API
    and is logged as a warning.
    """
    # Load the DynamicWindSkeletalData class
    wind_cls = None
    for class_path in (
        "/Script/DynamicWind.DynamicWindSkeletalData",
        "/Script/DynamicWind.DynamicWindData",
    ):
        try:
            wind_cls = unreal.load_class(None, class_path)
            if wind_cls is not None:
                break
        except Exception:
            continue

    if wind_cls is None:
        unreal.log_warning("[Wind] %s: DynamicWind plugin class not found" % label)
        return False

    # Retrieve or create the AssetUserData on the mesh
    wind_obj = None
    try:
        wind_obj = mesh.get_asset_user_data_of_class(wind_cls)
    except Exception:
        pass

    if wind_obj is None or isinstance(wind_obj, bool):
        try:
            mesh.add_asset_user_data_of_class(wind_cls)
        except Exception:
            pass
        try:
            wind_obj = mesh.get_asset_user_data_of_class(wind_cls)
        except Exception:
            pass

    # Fallback: iterate asset_user_data array
    if wind_obj is None or isinstance(wind_obj, bool):
        try:
            for ud in mesh.get_editor_property("asset_user_data"):
                if "DynamicWind" in type(ud).__name__:
                    wind_obj = ud
                    break
        except Exception:
            pass

    if wind_obj is None or isinstance(wind_obj, bool):
        unreal.log_warning("[Wind] %s: Could not create DynamicWindSkeletalData" % label)
        return False

    # Set scalar properties
    try:
        wind_obj.set_editor_property(
            "bIsGroundCover", wind_data.get("bIsGroundCover", False))
        wind_obj.set_editor_property(
            "GustAttenuation", wind_data.get("GustAttenuation", 0.0))
    except Exception as e:
        unreal.log_warning("[Wind] %s: Failed to set scalar props: %s" % (label, e))

    # Build and set SimulationGroups
    json_sim_groups = wind_data.get("SimulationGroups", [])
    sg_struct_cls = getattr(unreal, "DynamicWindSimulationGroupData", None)

    if sg_struct_cls is not None and json_sim_groups:
        new_groups = []
        for sg in json_sim_groups:
            elem = sg_struct_cls()
            for prop, val in sg.items():
                try:
                    elem.set_editor_property(prop, val)
                except Exception:
                    pass
            new_groups.append(elem)

        try:
            wind_obj.set_editor_property("SimulationGroups", new_groups)
        except Exception:
            # Fallback: clear existing + append
            try:
                arr = wind_obj.get_editor_property("SimulationGroups")
                while len(arr) > 0:
                    arr.pop()
                for elem in new_groups:
                    arr.append(elem)
                wind_obj.set_editor_property("SimulationGroups", arr)
            except Exception as e:
                unreal.log_warning(
                    "[Wind] %s: Failed to set SimulationGroups: %s" % (label, e))
                return False

    # Verify
    final = wind_obj.get_editor_property("SimulationGroups")
    num_groups = len(final) if final else 0
    num_joints = len(wind_data.get("Joints", []))

    if num_groups == 0:
        unreal.log_warning("[Wind] %s: SimulationGroups empty after set" % label)
        return False

    unreal.log(
        "[Wind] %s: %d simulation groups set, %d joints in JSON "
        "(per-bone mapping not settable via Python API)"
        % (label, num_groups, num_joints)
    )
    return True


def main():
    if not os.path.isdir(FOREST_ROOT):
        unreal.log_error("[Wind] Forest root does not exist: %s" % FOREST_ROOT)
        return

    wind_files = []
    for dirpath, _dirnames, filenames in os.walk(FOREST_ROOT):
        for fname in filenames:
            if fname.endswith(WIND_JSON_SUFFIX):
                wind_files.append(os.path.join(dirpath, fname))
    wind_files.sort()

    if not wind_files:
        unreal.log_warning(
            "[Wind] No *%s files found under %s"
            % (WIND_JSON_SUFFIX, FOREST_ROOT)
        )
        return

    unreal.log(
        "[Wind] Found %d wind JSON file(s) under %s"
        % (len(wind_files), FOREST_ROOT)
    )

    has_dw = _have_dynamic_wind()
    if not has_dw:
        unreal.log_error(
            "[Wind] DynamicWind plugin not available. "
            "Enable it in Edit > Plugins > Dynamic Wind."
        )
        return

    applied = 0
    failed = 0

    for wind_file in wind_files:
        json_dir = os.path.dirname(wind_file).replace("\\\\", "/")
        basename = os.path.basename(wind_file)
        stem = basename[: -len(".json")]

        try:
            with open(wind_file, "r") as f:
                wind_data = json.load(f)
        except Exception as _e:
            unreal.log_warning("[Wind] Could not read %s: %s" % (basename, _e))
            failed += 1
            continue

        mesh = _find_assembly_mesh(json_dir, stem)
        if mesh is None:
            failed += 1
            continue

        label = stem.replace("_stems_unreal_wind", "")

        if _apply_wind_data(mesh, wind_data, label):
            try:
                unreal.EditorAssetLibrary.save_loaded_asset(mesh)
            except Exception:
                pass
            applied += 1
        else:
            failed += 1

    unreal.log(
        "[Wind] Done: %d applied, %d failed out of %d total"
        % (applied, failed, len(wind_files))
    )


main()
'''


def generate_wind_import_script(
    output_dir: Path,
    forest_root: Path,
    import_base: str = "/Game/Assets/TheGrove",
) -> Path:
    """Write a UE Python script that imports DynamicWind data into skeletal meshes.

    The generated script walks ``forest_root`` at runtime (inside UE) for
    ``*_stems_unreal_wind.json`` files. For each, it locates the matching
    nanite assembly SkeletalMesh in the Content Browser and applies the
    wind simulation group data.

    Args:
        output_dir: Where to write the .py script (typically ``unreal_scripts/``).
        forest_root: Root of the growpy forest export (absolute path).
        import_base: UE Content Browser base path for tree assets.

    Returns:
        Path to the written script.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    script_path = output_dir / "growpy_wind_import.py"

    forest_root_str = str(forest_root.resolve()).replace("\\", "/")

    header = (
        f'FOREST_ROOT = r"{forest_root_str}"\n' f'IMPORT_BASE = "{import_base}"\n\n'
    )

    body = _WIND_IMPORT_PREAMBLE.format(
        script_path=str(script_path).replace("\\", "/"),
        suffix=WIND_JSON_SUFFIX,
    )

    script_path.write_text(header + body, encoding="utf-8")
    logger.info("Generated DynamicWind import script: %s", script_path)
    return script_path
