#!/usr/bin/env python3
"""Diagnose whether get_twig_locations() reflects pre- or post-cutoff twig counts.

Grows one tree, then builds the mesh twice with different build_cutoff_thickness
values.  Compares the twig counts from three sources:

  A) grove.get_twig_locations() before any build_models() call (if accessible)
  B) model.get_twig_locations()  after build with cutoff = 0
  C) model.get_twig_locations()  after build with configured cutoff
  D) face-attribute extraction count for B and C

If B == C the method reads from Grove's growth-simulation data (pre-cutoff).
If B != C it is generated by build_models() and is post-cutoff.

Usage:
    conda run -n growpy python src/growpy/tools/diagnose_twig_cutoff.py [species] [cycles]
    conda run -n growpy python src/growpy/tools/diagnose_twig_cutoff.py "European oak" 20 --cutoff 0.005
"""

import bpy

if hasattr(bpy.utils, "expose_bundled_modules"):
    bpy.utils.expose_bundled_modules()

import sys


def _face_twig_count(model) -> int:
    """Count faces whose face_attribute_twig_* value is > 0 (living types only)."""
    total = 0
    for attr in ("face_attribute_twig_long", "face_attribute_twig_short", "face_attribute_twig_upward"):
        vals = getattr(model, attr, None)
        if vals:
            total += sum(1 for v in vals if v > 0)
    return total


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Diagnose twig cutoff behaviour.")
    parser.add_argument("species", nargs="?", default="European oak")
    parser.add_argument("cycles", nargs="?", type=int, default=20)
    parser.add_argument("--cutoff", type=float, default=0.005,
                        help="build_cutoff_thickness to compare against zero (default 0.005)")
    args = parser.parse_args()

    from growpy.config import get_config, get_quality_preset
    from growpy.core.grove import add_tree_to_grove, create_grove

    cfg = get_config()
    qp = get_quality_preset(cfg.forest_quality)

    base_build_opts = {
        "resolution": qp.get("resolution", 16),
        "resolution_reduce": qp.get("resolution_reduce", 0.5),
        "build_blend": qp.get("build_blend", True),
        "build_end_cap": qp.get("build_end_cap", True),
        "build_cutoff_age": 0,
    }

    grove = create_grove(args.species)
    add_tree_to_grove(grove, (0.0, 0.0, 0.0))

    print(f"\nGrowing {args.species} for {args.cycles} cycles ...")
    for _ in range(args.cycles):
        grove.weigh_and_bend()
        grove.simulate(1)

    # --- A: try grove-level access before any build ---
    pre_build_count = None
    if hasattr(grove, "get_twig_locations"):
        locs = grove.get_twig_locations()
        pre_build_count = len(locs) // 3
        print(f"\n[A] grove.get_twig_locations() BEFORE build_models: {pre_build_count} twigs")
    else:
        print("\n[A] grove.get_twig_locations() not available before build_models()")

    # --- B: build with no cutoff ---
    models_no_cut = grove.build_models({**base_build_opts, "build_cutoff_thickness": 0.0})
    model_no_cut = models_no_cut[0]
    count_b_api = len(model_no_cut.get_twig_locations()) // 3
    count_b_face = _face_twig_count(model_no_cut)

    print(f"\n[B] build with cutoff=0.000")
    print(f"    get_twig_locations() : {count_b_api:>6} twigs")
    print(f"    face attributes      : {count_b_face:>6} faces marked")

    # --- C: build with configured cutoff ---
    models_cut = grove.build_models({**base_build_opts, "build_cutoff_thickness": args.cutoff})
    model_cut = models_cut[0]
    count_c_api = len(model_cut.get_twig_locations()) // 3
    count_c_face = _face_twig_count(model_cut)

    print(f"\n[C] build with cutoff={args.cutoff:.3f}")
    print(f"    get_twig_locations() : {count_c_api:>6} twigs")
    print(f"    face attributes      : {count_c_face:>6} faces marked")

    # --- D: low-resolution no-cutoff (tests resolution independence) ---
    low_res_opts = {
        "resolution": 4, "resolution_reduce": 1.0,
        "build_blend": False, "build_end_cap": False,
        "build_cutoff_age": 0, "build_cutoff_thickness": 0.0,
    }
    models_low_res = grove.build_models(low_res_opts)
    model_low_res = models_low_res[0]
    count_d_api = len(model_low_res.get_twig_locations()) // 3
    count_d_face = _face_twig_count(model_low_res)
    count_d_total = len(model_low_res.faces) if hasattr(model_low_res, "faces") else 0
    count_b_total = len(model_no_cut.faces) if hasattr(model_no_cut, "faces") else 0

    print(f"\n[D] low-res no-cutoff (res=4) -- resolution independence test")
    same = count_d_api == count_b_api
    print(f"    get_twig_locations() : {count_d_api:>6}  ({'SAME as B' if same else f'DIFFERS from B ({count_b_api})'})")
    print(f"    face attributes      : {count_d_face:>6} marked  /  {count_d_total} total  (B: {count_b_total} total)")

    # --- verdict ---
    print("\n--- VERDICT ---")
    if count_b_api == count_c_api:
        print("get_twig_locations() is INDEPENDENT of build_cutoff_thickness.")
        print("  -> Reads from Grove's growth-simulation data (pre-cutoff).")
        lost = count_b_face - count_c_face
        print(f"  -> Cutoff eliminated {lost} face-marked twigs ({100*lost/max(count_b_face,1):.1f}%).")
        print(f"  -> Surviving ratio: {count_c_face}/{count_b_api} = {count_c_face/max(count_b_api,1):.2%}")
        print("  -> No double-build needed.")
    else:
        diff = count_b_api - count_c_api
        print("get_twig_locations() CHANGES with build_cutoff_thickness (post-cutoff).")
        print(f"  -> Lost to cutoff: {diff} ({100*diff/max(count_b_api,1):.1f}% of full count).")
        if count_d_api == count_b_api:
            print("  -> Low-res pre-count (res=4) matches full-res: cheap double-build is viable.")
        else:
            print("  -> Low-res pre-count differs: must use full-res build or calibration constant.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
